      BLOCK DATA T2_HIST_DATA
      END
      LOGICAL FUNCTION T2_SET_HIST_DIR(CHDIR,CHOPT)
      WRITE(0,*)
     *'LOGICAL FUNCTION T2_SET_HIST_DIR(CHDIR,CHOPT)
     * called.'
      RETURN
      END
      INTEGER FUNCTION T2_HIST_ID ( )
      WRITE(0,*)
     *'INTEGER FUNCTION T2_HIST_ID ( )
     * called.'
      RETURN
      END 
      SUBROUTINE T2_HIST_PARSE_TYPE
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_PARSE_TYPE
     * called.'
      RETURN
      END
      SUBROUTINE T2_SET_MONITOR(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_SET_MONITOR(INFOIN,CARDIN)
     * called.'
      RETURN
      END

      SUBROUTINE T2_MONITOR_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_MONITOR_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_LABEL(STR,VAL,TEXT,CASE,N)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_LABEL(STR,VAL,TEXT,CASE,N)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_INIT
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_INIT
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_GET_STATISTICS(IDH)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_GET_STATISTICS(IDH)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_PARSE_NAME
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_PARSE_NAME
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_PARSE_AREA(INFOIN,CARDIN,LSET,LTRE)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_PARSE_AREA(INFOIN,CARDIN,LSET,LTRE)
     * called.'
      RETURN
      END
      SUBROUTINE T2_SHOW_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_SHOW_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIDOPT(IDH)
      WRITE(0,*)
     *'SUBROUTINE T2_HIDOPT(IDH)
     * called.'
      RETURN
      END
      SUBROUTINE T2_DELETE_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_DELETE_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_DO(INFOIN,CARDIN,QUERY,ROUTINE,OPER,IOPER,LOPER
     *)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_DO(INFOIN,CARDIN,QUERY,ROUTINE,OPER,IOPER,LOPER
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_TEST_STATUS(INFOIN,CARDIN,IDH)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_TEST_STATUS(INFOIN,CARDIN,IDH)
     * called.'
      RETURN
      END
      INTEGER FUNCTION T2_HIST_TYPE(IDH)
      WRITE(0,*)
     *'INTEGER FUNCTION T2_HIST_TYPE(IDH)
     * called.'
      RETURN
      END
      INTEGER FUNCTION T2_HIST_ID_LOCATION(I)
      WRITE(0,*)
     *'INTEGER FUNCTION T2_HIST_ID_LOCATION(I)
     * called.'
      RETURN
      END
      SUBROUTINE T2_SET_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_SET_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_TITLE
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_TITLE
     * called.'
      RETURN
      END
      LOGICAL FUNCTION T2_GET_TUPL(IDNEVT)
      WRITE(0,*)
     *'LOGICAL FUNCTION T2_GET_TUPL(IDNEVT)
     * called.'
      RETURN
      END
      SUBROUTINE T2_PRINT_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_PRINT_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HINDEX
      WRITE(0,*)
     *'SUBROUTINE T2_HINDEX
     * called.'
      RETURN
      END
      SUBROUTINE T2_HPRINT(I)
      WRITE(0,*)
     *'SUBROUTINE T2_HPRINT(I)
     * called.'
      RETURN
      END
      SUBROUTINE T2_DEFINE_HIST(INFOIN,CARDIN)
      WRITE(0,*)
     *'SUBROUTINE T2_DEFINE_HIST(INFOIN,CARDIN)
     * called.'
      RETURN
      END
      SUBROUTINE T2_CREATE_HIST_DIR(INFOIN,CARDIN,CHDIR)
      WRITE(0,*)
     *'SUBROUTINE T2_CREATE_HIST_DIR(INFOIN,CARDIN,CHDIR)
     * called.'
      RETURN
      END
      SUBROUTINE T2_SAVE_HIST(INFOIN,CARDIN,LSAVE)
      WRITE(0,*)
     *'SUBROUTINE T2_SAVE_HIST(INFOIN,CARDIN,LSAVE)
     * called.'
      RETURN
      END
      SUBROUTINE T2_READ_HIST(FILNAM,IOPER,INFOIN,CARDIN,IRDOPT,STYP)
      WRITE(0,*)
     *'SUBROUTINE T2_READ_HIST(FILNAM,IOPER,INFOIN,CARDIN,IRDOPT,STYP)
     * called.'
      RETURN
      END
      SUBROUTINE T2_HIST_GET_SECT(PAWC,I)
      WRITE(0,*)
     *'SUBROUTINE T2_HIST_GET_SECT(PAWC,I)
     * called.'
      RETURN
      END

      SUBROUTINE T2_SHOW_MONITOR
      IMPLICIT NONE
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      INTEGER MAXTUPL , MAX_STATS 
      PARAMETER (MAXTUPL=128)
      PARAMETER (MAX_STATS=12)
      CHARACTER*4 CETYPE(4)
      CHARACTER*8 CTUPL(MAXTUPL)
      CHARACTER*80 HNAME, TNAME, HTITL
      INTEGER NHNAME,NTNAME,NHTITL
      INTEGER T2BTRIM
      CHARACTER*6 CDIR(4)
      CHARACTER*128 CURDIR,SAVDIR,TSTDIR,TSTDIR2
      INTEGER SECT_OFFSET
      INTEGER IDVEC(19)
      INTEGER IHTYPE,ID,IDENT,ILOCS,NOPER
      INTEGER IDMIN,IDMAX,IVERSION,IOFSET,NTSTDIR,NTSTDIR2
      INTEGER IAD,IX,IY,IJUMP,NTUPL,ENTRYS,IETYPE,LHFILE
      INTEGER NTUPL1,NTUPL2
      LOGICAL MATCHC
      LOGICAL LEXIST,LHINIT,LEXACT,LTREE ,LENTRY,LSENT,LALL,LHIST,LMESH,
     *LNTUPL,LARRAY ,LTITLE,LILTUPL,LINDEX ,LAREA,LCHECK_MEM,LHWILD,LHTE
     *ST,LSTAT
      CHARACTER*80 SMON_OPTIONS(2)
      INTEGER NMON_OPTIONS(2),IMON_OPTIONS(2)
      REAL STATS(MAX_STATS)
      REAL XMIN,YMIN,ZMIN,XMAX,YMAX,ZMAX,XS,YS,VMIN,VMAX,HVERSION
      REAL VTUPL(MAXTUPL,2),LIMTUPL(MAXTUPL,2)
      INTEGER NLIMTUPL,ILIMTUPL(MAXTUPL)
      COMMON /T2HISTS/ HNAME, TNAME, HTITL, CETYPE, CTUPL
      COMMON /T2HISTC/ IHTYPE,ID,IDENT,ILOCS ,IDMIN,IDMAX,IVERSION,IOFSE
     *T ,IAD,IX,IY,IJUMP,IETYPE ,ENTRYS,XMIN,YMIN,XMAX,YMAX,XS,YS,ZMIN,Z
     *MAX,VMIN,VMAX ,STATS,HVERSION ,IDVEC,SECT_OFFSET,NOPER ,NTUPL,NTUP
     *L1,NTUPL2,VTUPL,NLIMTUPL,ILIMTUPL,LIMTUPL ,LEXIST,LHINIT,LHFILE,LE
     *XACT,LTREE ,LENTRY,LSENT,LALL,LHIST,LMESH,LNTUPL,LARRAY,LTITLE ,LI
     *LTUPL,LINDEX,LAREA,LCHECK_MEM,LHWILD,LHTEST,LSTAT ,NMON_OPTIONS,IM
     *ON_OPTIONS ,NHNAME,NTNAME ,CURDIR,SAVDIR,NTSTDIR,TSTDIR,NTSTDIR2,T
     *STDIR2,CDIR ,SMON_OPTIONS
      LOGICAL LAPPEN, LCONF, LMONITOR, LCHECK, LLOG
      INTEGER N1,N2,N3,N4,NS1,NS2
      REAL TLIM(3,2)
      COMMON /T2SELECT/N1 ,N2 ,N3 ,N4 ,NS1 ,NS2 ,TLIM ,LMONITOR ,LAPPEN
     * ,LCONF ,LLOG ,LCHECK
      CHARACTER*80 PRMP1, PRMP2
      INTEGER NPRMP1, NPRMP2
      COMMON /T2PRMP/NPRMP1, PRMP1, NPRMP2, PRMP2
      CHARACTER*10 STYPE(2)
      CHARACTER*10 SOPTIONS(5)
      INTEGER I,J
      DATA STYPE/'DATA','MESH'/
      DATA SOPTIONS/'HISTOGRAM','PLOT','JOIN','CONTOUR','BIN'/
      WRITE(6,*)'  Monitor   Type of plot'
      DO 10151 I=1,2
      J=IMON_OPTIONS(I)
      WRITE(6,*) '   ',STYPE(I),'  ',SOPTIONS(J)
      J=T2BTRIM(SMON_options(I))
      IF (SMON_OPTIONS(I).ne.' ') WRITE(6,*) '     "'//SMON_OPTIONS(I)(:
     *J)//'"'
10151 CONTINUE
10152 CONTINUE
      END
