C        MORTRAN 2.79 (BRACKETED KEYWORD MACROS OF 09/28/81)          
      BLOCK DATA T2SETC
      IMPLICIT NONE
      LOGICAL T,F
      PARAMETER (T=.TRUE.)
      PARAMETER (F=.FALSE.)
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL HNONE
      INTEGER MAXTER, MAX_FIT_LIM 
      PARAMETER ( MAXTER = 20 )
      PARAMETER ( MAX_FIT_LIM = 12 )
      DOUBLE PRECISION COFF(MAXTER), DCOFF(MAXTER), ACOEF(MAXTER)
      DOUBLE PRECISION CHISQR, FTEST, XF(MAXTER), DACOEF(MAXTER), RMUL
      DOUBLE PRECISION EMATRX(MAXTER,MAXTER),D_CHISQ
      REAL XOFF, FIT_LIM(3,MAX_FIT_LIM)
      INTEGER NTERMS, IFIT, NFIT, NPFIT, NCOFF, NEXTER, NEXPR(MAXTER+1)
      INTEGER I_FIT(2,MAXTER), IDEP_FIT
      INTEGER N1_FIT, N2_FIT, N3_FIT, N4_FIT, NS1_FIT, NS2_FIT
      INTEGER N_FIT_LIM, IMESH_FIT
      LOGICAL LCOF1(MAXTER), LCOFF(MAXTER), LFIT(MAXTER), LXLOG, LYLOG
      LOGICAL LDY_FIT
      COMMON /T2FITS/ COFF, DCOFF, ACOEF, CHISQR, FTEST, XF, DACOEF, RMU
     *L, EMATRX, D_CHISQ, XOFF, FIT_LIM, NTERMS, IFIT, NFIT, NPFIT, NCOF
     *F, NEXTER, NEXPR, I_FIT, IDEP_FIT,  N1_FIT, N2_FIT, N3_FIT, N4_FI
     *T, NS1_FIT, NS2_FIT, N_FIT_LIM, IMESH_FIT, LCOF1, LCOFF, LFIT, LXL
     *OG, LYLOG, LDY_FIT 
      CHARACTER*80 FITSTR
      CHARACTER*(512+8+2*MAXTER) SEXPR
      COMMON /T2FITT/FITSTR, SEXPR
      LOGICAL DFLAGS(200),DSCREV(3)
      COMMON /T2FLGD/DFLAGS,DSCREV
      REAL DTITLIN(4), DTITFAC(4), DTITMAR(4)
      INTEGER DGRDTYP, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DSHADOWTYP,DS
     *HADOWTEX, IFLDDF(19), NDDIMNS, IDTXPRI, IDTXSEC, LINCLF, LINTXF,
     * LINWDF, DNONLN(3), DNXYZ1(3), DNXYZ2(3), DLABTEX, DTICTEX, DNPAT
     *RN(30), DLBLCHR(3), ND_CYCLE, IDTX_CYCLE(MAX_CYCLE)
      REAL DSYM_CYCLE(MAX_CYCLE)
      REAL DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ(2,3), DASIZE, DAFLARE, D
     *SMSZDF, DORAXES(3), DEYEDIR(3), DVUEDIR(3), DVUECEN(3), DVERTCL(3
     *), DEYESEP, DSCRD, DSCRZ, DEYEDIS, DEYEPNT(3), DBARSIZ(3), DBARBR
     *K(3), DTIKSIZ(3), DXYZBS(3), DTTHETA, DTPHI, DFRELBL(4), DPATRN(2
     *0,30), DSCLPRM(10,3), DWINDOW(4), DSCREEN(2), DSYMBOL, DNOSYMB, 
     *DAXANG(3), DLBLSIZ, DSYMSIZ, DXYZLIM(3,2), DFACTXY(19), DRADANG,
     * DDSCAL, DPATSZ, DTITINX, DTIKFAC, DSYDIR(3), DGRDIR(3)
      COMMON /T2COMD/ DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ, DASIZE, DAFLA
     *RE, DSMSZDF, DORAXES, DEYEDIR, DVUEDIR, DVUECEN, DVERTCL, DEYESE
     *P, DSCRD, DSCRZ, DEYEDIS, DEYEPNT, DBARSIZ, DTIKSIZ, DXYZBS, DTTH
     *ETA, DTPHI, DFRELBL, DNPATRN, DPATRN, DSCLPRM, DWINDOW, DSCREEN,
     * DSYMBOL, DNOSYMB, DAXANG, DLBLSIZ, DSYMSIZ, DXYZLIM, DGRDTYP, D
     *FACTXY, IFLDDF, NDDIMNS, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DRADA
     *NG, DDSCAL, DNONLN, DNXYZ1, DNXYZ2, LINCLF, LINTXF, LINWDF, DLABT
     *EX, DTICTEX, DPATSZ, IDTXPRI, IDTXSEC, DTITLIN, DTITINX, DLBLCHR,
     * DTITFAC, DTITMAR, DTIKFAC, DSYDIR, DGRDIR, ND_CYCLE, IDTX_CYCLE,
     * DSYM_CYCLE, DBARBRK,  DSHADOWTYP,DSHADOWTEX
      CHARACTER*80 PRMP1, PRMP2
      INTEGER NPRMP1, NPRMP2
      COMMON /T2PRMP/NPRMP1, PRMP1, NPRMP2, PRMP2
      INTEGER NSETD 
      PARAMETER (NSETD=19+9)
      INTEGER ISETD(NSETD),NINCR0,NINCR1,NINCR2,IBTYPE
      INTEGER I1,I2,I3,I4,I5,I6,I7,IM,NP,NL,IENDAT,IBGDAT
      INTEGER I_NDX,I_NDY,I_NDZ
      INTEGER N_SYMBOL 
      INTEGER N_XDATA 
      INTEGER N_DXDATA 
      INTEGER N_NDXDATA 
      INTEGER N_YDATA 
      INTEGER N_DYDATA 
      INTEGER N_NDYDATA 
      INTEGER N_ZDATA 
      INTEGER N_DZDATA 
      INTEGER N_NDZDATA 
      INTEGER N_UDATA 
      INTEGER N_DUDATA 
      INTEGER N_NDUDATA 
      INTEGER N_VDATA 
      INTEGER N_DVDATA 
      INTEGER N_NDVDATA 
      INTEGER N_WDATA 
      INTEGER N_DWDATA 
      INTEGER N_NDWDATA 
      INTEGER NCMAX 
      INTEGER NCSIZE 
      INTEGER NBTYPE 
      INTEGER NINDAT 
      INTEGER NSDATA 
      INTEGER NXDATA 
      INTEGER NDXDATA 
      INTEGER NNDXDATA 
      INTEGER NYDATA 
      INTEGER NDYDATA 
      INTEGER NNDYDATA 
      INTEGER NZDATA 
      INTEGER NDZDATA 
      INTEGER NNDZDATA 
      INTEGER NPDATA 
      INTEGER NLDATA 
      INTEGER NMDATA 
      INTEGER NBGDAT 
      INTEGER NENDAT 
      PARAMETER (N_SYMBOL=1) 
      PARAMETER (N_XDATA=2) 
      PARAMETER (N_DXDATA=3) 
      PARAMETER (N_NDXDATA=4) 
      PARAMETER (N_YDATA=5) 
      PARAMETER (N_DYDATA=6) 
      PARAMETER (N_NDYDATA=7) 
      PARAMETER (N_ZDATA=8) 
      PARAMETER (N_DZDATA=9) 
      PARAMETER (N_NDZDATA=10) 
      PARAMETER (N_UDATA=11) 
      PARAMETER (N_DUDATA=12) 
      PARAMETER (N_NDUDATA=13) 
      PARAMETER (N_VDATA=14) 
      PARAMETER (N_DVDATA=15) 
      PARAMETER (N_NDVDATA=16) 
      PARAMETER (N_WDATA=17) 
      PARAMETER (N_DWDATA=18) 
      PARAMETER (N_NDWDATA=19) 
      PARAMETER (NCMAX=6) 
      PARAMETER (NCSIZE=3) 
      PARAMETER (NBTYPE=1) 
      PARAMETER (NINDAT=2) 
      PARAMETER (NSDATA=5) 
      PARAMETER (NXDATA=NSDATA+1) 
      PARAMETER (NDXDATA=NXDATA+1) 
      PARAMETER (NNDXDATA=NXDATA+2) 
      PARAMETER (NYDATA=NXDATA+NCSIZE) 
      PARAMETER (NDYDATA=NYDATA+1) 
      PARAMETER (NNDYDATA=NYDATA+2) 
      PARAMETER (NZDATA=NYDATA+NCSIZE) 
      PARAMETER (NDZDATA=NZDATA+1) 
      PARAMETER (NNDZDATA=NZDATA+2) 
      PARAMETER (NPDATA=NSDATA+19) 
      PARAMETER (NLDATA=NPDATA+1) 
      PARAMETER (NMDATA=NLDATA+1) 
      PARAMETER (NBGDAT=NMDATA+1) 
      PARAMETER (NENDAT=NBGDAT+1) 
      EQUIVALENCE (IBTYPE,ISETD(NBTYPE))
      EQUIVALENCE (NINCR0,ISETD(NINDAT))
      EQUIVALENCE (NINCR1,ISETD(NINDAT+1))
      EQUIVALENCE (NINCR2,ISETD(NINDAT+2))
      EQUIVALENCE (I7,ISETD(NSDATA))
      EQUIVALENCE (I1,ISETD(NXDATA))
      EQUIVALENCE (I4,ISETD(NDXDATA))
      EQUIVALENCE (I2,ISETD(NYDATA))
      EQUIVALENCE (I5,ISETD(NDYDATA))
      EQUIVALENCE (I3,ISETD(NZDATA))
      EQUIVALENCE (I6,ISETD(NDZDATA))
      EQUIVALENCE (I_NDX,ISETD(NNDXDATA))
      EQUIVALENCE (I_NDY,ISETD(NNDYDATA))
      EQUIVALENCE (I_NDZ,ISETD(NNDZDATA))
      EQUIVALENCE (NP,ISETD(NPDATA))
      EQUIVALENCE (NL,ISETD(NLDATA))
      EQUIVALENCE (IM,ISETD(NMDATA))
      EQUIVALENCE (IBGDAT,ISETD(NBGDAT))
      EQUIVALENCE (IENDAT,ISETD(NENDAT))
      REAL PLIM(4,4),ZSCRN(2),XLLINE,YLLINE,XTLINE,YTLINE,XFRMFC, PAT(2
     *0),PATCUM,PATTOT,PATMOD,CCSCIS(4),DISPL, RESOL(2)
      INTEGER NPTS,IDDEVC,IPAT,NPAT,LMOVE,IROTAX,IROTAF
      COMMON/TXCOM/PLIM,ZSCRN, XLLINE,YLLINE,XTLINE,YTLINE,XFRMFC, IPA
     *T,NPAT,PAT,PATTOT, NPTS,IDDEVC,CCSCIS,LMOVE,IROTAX,DISPL,IROTAF,P
     *ATCUM,PATMOD, RESOL
      INTEGER LISTPT,NPTMAX,NDSETS
C     REAL DATBUF(10248)
      REAL DATBUF(262144)
      COMMON /T2XPNT/ LISTPT,NPTMAX,NDSETS,DATBUF
      EQUIVALENCE (DATBUF(1),HNONE)
      INTEGER REMAIN_VAR 
      PARAMETER (REMAIN_VAR=19-5) 
      REAL SYM0,SYM1,SYM2,SYM3,SYM4,SYM5,SYM6,SYM7,SYM8,SYM9
      INTEGER CZERO, COH
      PARAMETER (CZERO = Z'30')
      PARAMETER (COH = Z'4F')

      PARAMETER (SYM0 = COH+256*(CZERO+0.))
      PARAMETER (SYM1 = COH+256*(CZERO+1.))
      PARAMETER (SYM2 = COH+256*(CZERO+2.))
      PARAMETER (SYM3 = COH+256*(CZERO+3.))
      PARAMETER (SYM4 = COH+256*(CZERO+4.))
      PARAMETER (SYM5 = COH+256*(CZERO+5.))
      PARAMETER (SYM6 = COH+256*(CZERO+6.))
      PARAMETER (SYM7 = COH+256*(CZERO+7.))
      PARAMETER (SYM8 = COH+256*(CZERO+8.))
      PARAMETER (SYM9 = COH+256*(CZERO+9.))

C      PARAMETER (SYM0=FLOAT(Z'304F')) !ICHAR('O')+256*ICHAR('0'))
C      PARAMETER (SYM1=FLOAT(Z'314F')) !ICHAR('O')+256*ICHAR('1'))
C      PARAMETER (SYM2=FLOAT(Z'324F')) !ICHAR('O')+256*ICHAR('2'))
C      PARAMETER (SYM3=FLOAT(Z'334F')) !ICHAR('O')+256*ICHAR('3'))
C      PARAMETER (SYM4=FLOAT(Z'344F')) !ICHAR('O')+256*ICHAR('4'))
C      PARAMETER (SYM5=FLOAT(Z'354F')) !ICHAR('O')+256*ICHAR('5'))
C      PARAMETER (SYM6=FLOAT(Z'364F')) !ICHAR('O')+256*ICHAR('6'))
C      PARAMETER (SYM7=FLOAT(Z'374F')) !ICHAR('O')+256*ICHAR('7'))
C      PARAMETER (SYM8=FLOAT(Z'384F')) !ICHAR('O')+256*ICHAR('8'))
C      PARAMETER (SYM9=FLOAT(Z'394F')) !ICHAR('O')+256*ICHAR('9'))
      INTEGER M1_CYCLE , M2_CYCLE 
      PARAMETER (M1_CYCLE=MAX_CYCLE-7 ) 
      PARAMETER (M2_CYCLE=MAX_CYCLE-10) 
      DATA HNONE /-666.666/
      DATA EXYZLIM(1,1) /-666.666/
      DATA LISTPT/2/
C     DATA NPTMAX/10248/
      DATA NPTMAX/262144/
      DATA IBLKTP/1/
      DATA BUFFER/400*0.0/
      DATA MAXSTR/0/
      DATA LINEAR/-1,-1,-1,0/
      DATA NONLIN/-1,-1,-1,1/
      DATA LTRAP /.false./
      DATA LSYERR/.false./
      DATA NDSETS/0/
      DATA SEXPR/' '/
      DATA NEXTER/0/
      DATA NTERMS/0/
      DATA REVLEV/5.12/
      DATA LEVREP/0/
      DATA IREPCT/MAXREP*0/
      DATA STRNG/' '/
      DATA NSTRNG/0/
      DATA STJOU/' '/
      DATA NSTJOU/0/
      DATA NPRMP1/4/,PRMP1/'TD: '/
      DATA NPRMP2/7/,PRMP2/'PAUSE: '/
      DATA NPOINT/0/
      DATA NMESH0,NMESH1,NMESH2/1,0,0/
C     DATA IVRPTR/11*1,3*2,10248/
      DATA IVRPTR/11*1,3*2,262144/
      DATA I_VORDER(1,1) /N_SYMBOL/
      DATA I_VORDER(2,1) /N_XDATA/
      DATA I_VORDER(3,1) /N_DXDATA/
      DATA I_VORDER(4,1) /N_YDATA/
      DATA I_VORDER(5,1) /N_DYDATA/
      DATA I_VORDER(6,1) /N_ZDATA/
      DATA I_VORDER(7,1) /N_DZDATA/
      DATA I_VORDER(8,1) /N_NDXDATA/
      DATA I_VORDER(9,1) /N_NDYDATA/
      DATA I_VORDER(10,1) /N_NDZDATA/
      DATA I_VORDER(11,1) /N_UDATA/
      DATA I_VORDER(12,1) /N_DUDATA/
      DATA I_VORDER(13,1) /N_NDUDATA/
      DATA I_VORDER(14,1) /N_VDATA/
      DATA I_VORDER(15,1) /N_DVDATA/
      DATA I_VORDER(16,1) /N_NDVDATA/
      DATA I_VORDER(17,1) /N_WDATA/
      DATA I_VORDER(18,1) /N_DWDATA/
      DATA I_VORDER(19,1) /N_NDWDATA/
      DATA I_VORDER(N_SYMBOL,2) /1/
      DATA I_VORDER(N_XDATA,2) /2/
      DATA I_VORDER(N_DXDATA,2) /3/
      DATA I_VORDER(N_YDATA,2) /4/
      DATA I_VORDER(N_DYDATA,2) /5/
      DATA I_VORDER(N_ZDATA,2) /6/
      DATA I_VORDER(N_DZDATA,2) /7/
      DATA I_VORDER(N_NDXDATA,2) /8/
      DATA I_VORDER(N_NDYDATA,2) /9/
      DATA I_VORDER(N_NDZDATA,2) /10/
      DATA I_VORDER(N_UDATA,2) /11/
      DATA I_VORDER(N_DUDATA,2) /12/
      DATA I_VORDER(N_NDUDATA,2) /13/
      DATA I_VORDER(N_VDATA,2) /14/
      DATA I_VORDER(N_DVDATA,2) /15/
      DATA I_VORDER(N_NDVDATA,2) /16/
      DATA I_VORDER(N_WDATA,2) /17/
      DATA I_VORDER(N_DWDATA,2) /18/
      DATA I_VORDER(N_NDWDATA,2) /19/
      DATA NINCR/5/
      DATA IVARBL(1) /N_SYMBOL/
      DATA IVARBL(2) /N_XDATA /
      DATA IVARBL(3) /N_DXDATA/
      DATA IVARBL(4) /N_YDATA /
      DATA IVARBL(5) /N_DYDATA/
      DATA IVPTR(N_SYMBOL) /1/
      DATA IVPTR(N_XDATA) /2/
      DATA IVPTR(N_DXDATA) /3/
      DATA IVPTR(N_YDATA) /4/
      DATA IVPTR(N_DYDATA) /5/
      DATA IVPTR(N_ZDATA) /0/
      DATA IVPTR(N_DZDATA) /0/
      DATA IVPTR(N_NDXDATA) /0/
      DATA IVPTR(N_NDYDATA) /0/
      DATA IVPTR(N_NDZDATA) /0/
      DATA IVPTR(N_UDATA) /0/
      DATA IVPTR(N_DUDATA) /0/
      DATA IVPTR(N_NDUDATA) /0/
      DATA IVPTR(N_VDATA) /0/
      DATA IVPTR(N_DVDATA) /0/
      DATA IVPTR(N_NDVDATA) /0/
      DATA IVPTR(N_WDATA) /0/
      DATA IVPTR(N_DWDATA) /0/
      DATA IVPTR(N_NDWDATA) /0/
      DATA NFIELD /5/
      DATA IFIELD(N_XDATA ) /1/
      DATA IFIELD(N_YDATA ) /2/
      DATA IFIELD(N_DXDATA) /3/
      DATA IFIELD(N_DYDATA) /4/
      DATA IFIELD(N_SYMBOL) /5/
      DATA IMONTH/1/,IDAY/1/,IYEAR/0/
      DATA FACTXY /19*1.0/
      DATA TITSIZ /2.0/
      DATA TITLIN /1.2,2.0,2*1.2/
      DATA TITFAC /3*1.0,1.5/
      DATA TITMAR/4*0.025/
      DATA TITINX /2./
      DATA XYZLIM/6*0./
      DATA LETSET /2/
      DATA INPFMT/'(512A1)'/
      DATA INPFIL/9/
      DATA ERRFIL/6/
      DATA IPATRN/1/
      DATA NPATRN/30*0/  PATRN(1,1) /1.0E10/
      DATA PATSZ/0.1/
      DATA LENCRD/512/
      DATA LINTEX/4/
      DATA LINWID/2/
      DATA LINCOL/1/
      DATA MAX_SUBST/1000/
      DATA MAXLNS,LINES/0,0/
      DATA MXECHO /20/
      DATA NOSYMB/0./,SYMBOL/0./
      DATA SYDIR/0.,-1.,0./
      DATA GRDIR/3*0.0/
      DATA BARSIZ /3*0.1/
      DATA BARBRK /3*0/
      DATA TIKSIZ /3*0.1/
      DATA TIKFAC /3.0/
      DATA NXYZ1/3*0/,NXYZ2/3*0/
      DATA NXYZDEF1/6,0,0,7*6/, NXYZDEF2/-5,0,0,2*-5,-6,4*-5/
      DATA SCLPRM(1,1)/10./,SCLPRM(1,2)/10./,SCLPRM(1,3)/10./
      DATA XYPART/4*1.0/
      DATA WINLIM/0,0,13.,10./
      DATA WINREL(1,1,1),WINREL(2,1,1),WINREL(1,2,1),WINREL(2,2,1)/4*1.0
     */
      DATA IWINLEV/1/
      DATA LBLCHR/3*6/
      DATA FRELBL/4*1./
      DATA LBLSIZ/2.0/
      DATA SYMSIZ/2.0/,SMSZDF/2.0/
      DATA FMARKER/24*1.0E35/
      DATA H2STAT/12*0.0/
      DATA LSCREV/3*F/
      DATA FILL_ANGLE/-.7071,.7071,0.,1./
      DATA FILL_WIDTH/2*0.1,2*0/
      DATA IFILE_CASE/1/
      DATA FLAGS/  T,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,T,T, T,T,F,F,T,F
     *,F,F,F,F, F,T,T,T,T,T,T,F,F,T, T,T,T,T,T,T,T,T,T,T, T,T,F,F,F,F,F,
     *F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F
     *,F, F,T,F,T,F,F,T,T,F,T, F,F,F,F,T,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F,
     * F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,
     *F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F
     *,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F/
      DATA LHANDL/.true./
      DATA PXNAME /' '/
      DATA MARGIN/4*0.0/
      DATA WORLD /13.,10.,10./
      DATA REDUCE /0.,4*1./
      DATA PSCR/13.,10./
      DATA SCREEN/13.,10./
      DATA GRDTYP/0/
      DATA GRDTEX/0/
      DATA GRDSYM/12367./
      DATA GRDSIZ/2.0/
      DATA SHADOWTYP/0/
      DATA SHADOWTEX/0/
      DATA OUTTEX/256/
      DATA ITXSEC/64/
      DATA IDTX_CYCLE/2112,3776,1664,3008,1280,3328,768 ,M1_CYCLE*768/
      DATA ITX_CYCLE /2112,3776,1664,3008,1280,3328,768 ,M1_CYCLE*768/
      DATA DSYM_CYCLE/SYM0,SYM1,SYM2,SYM3,SYM4,SYM5,SYM6,SYM7,SYM8,SYM9,
     * M2_CYCLE*SYM9/
      DATA SYM_CYCLE /SYM0,SYM1,SYM2,SYM3,SYM4,SYM5,SYM6,SYM7,SYM8,SYM9,
     * M2_CYCLE*SYM9/
      DATA ND_CYCLE/5/
      DATA N_CYCLE/5/
      DATA IAXTEX/256/
      DATA TITEX/256/
      DATA LABTEX/256/
      DATA TICTEX/0/
      DATA ORAXES/0.,0.,0./
      DATA EYEDIR/0.,0.,0./
      DATA VUECEN/0.,0.,0./
      DATA VERTCL/0.,0.,0./
      DATA TTHETA/30./,TPHI/60./
      DATA EYEDIS/35./,EYESEP /0./,SCRD/-18./
      DATA TITX/0.1/, TITY/11.7/, TITZ/0.0/
      DATA TITX1/0.1/, TITY1/11.7/
      DATA TITCON(1),TITCON(2),TITCON(3),TITCON(4),TITCON(5)  /2.0,0.,0.
     *,2.,0./, ITCNTR/0/,ITITDT/0,0,0/
      DATA LTDATA/.false./
      DATA RADRMN/0./,RADANG/0.0174532925/,RADAMN/0./
      DATA CIRSIZ/6*1./
      DATA ASIZE/2.0/,AFLARE/0.5/
      DATA IDIMNS/2/,NDIMNS/0,0,2/,NDDIMNS/0/
      DATA IPROP,IHTEX,IBLINK /3*0/
      DATA IERASE/0/
      DATA C_FILE/' '/
      DATA C_NAME/' '/
      DATA C_SELECT/' '/
      DATA IFLDDF(N_XDATA ) /1/
      DATA IFLDDF(N_YDATA ) /2/
      DATA IFLDDF(N_DXDATA) /3/
      DATA IFLDDF(N_DYDATA) /4/
      DATA IFLDDF(N_SYMBOL) /5/
      DATA DGRDTYP/0/
      DATA DGRDTEX/0/
      DATA DGRDSYM/12367./
      DATA DGRDSIZ/2.0/
      DATA DSHADOWTYP/0/
      DATA DSHADOWTEX/0/
      DATA DOUTTEX/256/
      DATA IDTXSEC/64/
      DATA IDAXTEX/256/
      DATA DTITEX/256/
      DATA DLABTEX/256/
      DATA DTICTEX/0/
      DATA DSYMBOL/0./
      DATA DSYDIR/0.,-1.,0./
      DATA DGRDIR/3*0.0/
      DATA DRADANG/0.0174532925/
      DATA DTIKFAC/3.0/
      DATA DTIKSIZ/3*0.1/, DBARSIZ/3*0.1/, DEYESEP/0./, DEYEDIS/35./, DS
     *CRD/-18./, DVERTCL/3*0./, DEYEDIR/3*0./, DVUECEN/3*-77777./, DORAX
     *ES/3*0./, DTTHETA/30./, DTPHI/60./
      DATA DBARBRK /3*0/
      DATA DCIRSIZ/6*1.0/, DTITSIZ/2.0/, DLBLSIZ/2.0/
      DATA DAXANG/3*720.0/  DFACTXY /19*1./  DNONLN/3*-1/,DNXYZ1/3*0/,DN
     *XYZ2/3*0/  
      DATA DSCLPRM(1,1)/10./,DSCLPRM(1,2)/10./,DSCLPRM(1,3)/10./
      DATA DLBLCHR/3*6/
      DATA DFRELBL/4*1./
      DATA DTITLIN/1.2,2.0,2*1.2/
      DATA DTITFAC /3*1.0,1.5/
      DATA DTITMAR/4*0.025/
      DATA DTITINX/2./
      DATA LINTXF/4/
      DATA LINWDF/2/
      DATA LINCLF/1/
      DATA DNPATRN/30*0/  DPATRN(1,1) /1./
      DATA DPATSZ/0.1/
      DATA DASIZE/2.0/,DAFLARE/0.5/
      DATA DSCREV/3*F/
      DATA DFLAGS/  T,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,T,T, T,T,F,F,T,
     *F,F,F,F,F, F,T,T,T,T,T,T,F,F,T, T,T,T,T,T,T,T,T,T,T, T,T,F,F,F,F,F
     *,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,
     *F,F, F,T,F,T,F,F,T,T,F,T, F,F,F,F,T,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F
     *, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F
     *,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,
     *F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F/
      END
      SUBROUTINE TDREST
      IMPLICIT NONE
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      LOGICAL DFLAGS(200),DSCREV(3)
      COMMON /T2FLGD/DFLAGS,DSCREV
      REAL DTITLIN(4), DTITFAC(4), DTITMAR(4)
      INTEGER DGRDTYP, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DSHADOWTYP,DS
     *HADOWTEX, IFLDDF(19), NDDIMNS, IDTXPRI, IDTXSEC, LINCLF, LINTXF,
     * LINWDF, DNONLN(3), DNXYZ1(3), DNXYZ2(3), DLABTEX, DTICTEX, DNPAT
     *RN(30), DLBLCHR(3), ND_CYCLE, IDTX_CYCLE(MAX_CYCLE)
      REAL DSYM_CYCLE(MAX_CYCLE)
      REAL DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ(2,3), DASIZE, DAFLARE, D
     *SMSZDF, DORAXES(3), DEYEDIR(3), DVUEDIR(3), DVUECEN(3), DVERTCL(3
     *), DEYESEP, DSCRD, DSCRZ, DEYEDIS, DEYEPNT(3), DBARSIZ(3), DBARBR
     *K(3), DTIKSIZ(3), DXYZBS(3), DTTHETA, DTPHI, DFRELBL(4), DPATRN(2
     *0,30), DSCLPRM(10,3), DWINDOW(4), DSCREEN(2), DSYMBOL, DNOSYMB, 
     *DAXANG(3), DLBLSIZ, DSYMSIZ, DXYZLIM(3,2), DFACTXY(19), DRADANG,
     * DDSCAL, DPATSZ, DTITINX, DTIKFAC, DSYDIR(3), DGRDIR(3)
      COMMON /T2COMD/ DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ, DASIZE, DAFLA
     *RE, DSMSZDF, DORAXES, DEYEDIR, DVUEDIR, DVUECEN, DVERTCL, DEYESE
     *P, DSCRD, DSCRZ, DEYEDIS, DEYEPNT, DBARSIZ, DTIKSIZ, DXYZBS, DTTH
     *ETA, DTPHI, DFRELBL, DNPATRN, DPATRN, DSCLPRM, DWINDOW, DSCREEN,
     * DSYMBOL, DNOSYMB, DAXANG, DLBLSIZ, DSYMSIZ, DXYZLIM, DGRDTYP, D
     *FACTXY, IFLDDF, NDDIMNS, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DRADA
     *NG, DDSCAL, DNONLN, DNXYZ1, DNXYZ2, LINCLF, LINTXF, LINWDF, DLABT
     *EX, DTICTEX, DPATSZ, IDTXPRI, IDTXSEC, DTITLIN, DTITINX, DLBLCHR,
     * DTITFAC, DTITMAR, DTIKFAC, DSYDIR, DGRDIR, ND_CYCLE, IDTX_CYCLE,
     * DSYM_CYCLE, DBARBRK,  DSHADOWTYP,DSHADOWTEX
      LOGICAL T,F
      INTEGER NSETD 
      PARAMETER (NSETD=19+9)
      INTEGER ISETD(NSETD),NINCR0,NINCR1,NINCR2,IBTYPE
      INTEGER I1,I2,I3,I4,I5,I6,I7,IM,NP,NL,IENDAT,IBGDAT
      INTEGER I_NDX,I_NDY,I_NDZ
      INTEGER N_SYMBOL 
      INTEGER N_XDATA 
      INTEGER N_DXDATA 
      INTEGER N_NDXDATA 
      INTEGER N_YDATA 
      INTEGER N_DYDATA 
      INTEGER N_NDYDATA 
      INTEGER N_ZDATA 
      INTEGER N_DZDATA 
      INTEGER N_NDZDATA 
      INTEGER N_UDATA 
      INTEGER N_DUDATA 
      INTEGER N_NDUDATA 
      INTEGER N_VDATA 
      INTEGER N_DVDATA 
      INTEGER N_NDVDATA 
      INTEGER N_WDATA 
      INTEGER N_DWDATA 
      INTEGER N_NDWDATA 
      INTEGER NCMAX 
      INTEGER NCSIZE 
      INTEGER NBTYPE 
      INTEGER NINDAT 
      INTEGER NSDATA 
      INTEGER NXDATA 
      INTEGER NDXDATA 
      INTEGER NNDXDATA 
      INTEGER NYDATA 
      INTEGER NDYDATA 
      INTEGER NNDYDATA 
      INTEGER NZDATA 
      INTEGER NDZDATA 
      INTEGER NNDZDATA 
      INTEGER NPDATA 
      INTEGER NLDATA 
      INTEGER NMDATA 
      INTEGER NBGDAT 
      INTEGER NENDAT 
      PARAMETER (N_SYMBOL=1) 
      PARAMETER (N_XDATA=2) 
      PARAMETER (N_DXDATA=3) 
      PARAMETER (N_NDXDATA=4) 
      PARAMETER (N_YDATA=5) 
      PARAMETER (N_DYDATA=6) 
      PARAMETER (N_NDYDATA=7) 
      PARAMETER (N_ZDATA=8) 
      PARAMETER (N_DZDATA=9) 
      PARAMETER (N_NDZDATA=10) 
      PARAMETER (N_UDATA=11) 
      PARAMETER (N_DUDATA=12) 
      PARAMETER (N_NDUDATA=13) 
      PARAMETER (N_VDATA=14) 
      PARAMETER (N_DVDATA=15) 
      PARAMETER (N_NDVDATA=16) 
      PARAMETER (N_WDATA=17) 
      PARAMETER (N_DWDATA=18) 
      PARAMETER (N_NDWDATA=19) 
      PARAMETER (NCMAX=6) 
      PARAMETER (NCSIZE=3) 
      PARAMETER (NBTYPE=1) 
      PARAMETER (NINDAT=2) 
      PARAMETER (NSDATA=5) 
      PARAMETER (NXDATA=NSDATA+1) 
      PARAMETER (NDXDATA=NXDATA+1) 
      PARAMETER (NNDXDATA=NXDATA+2) 
      PARAMETER (NYDATA=NXDATA+NCSIZE) 
      PARAMETER (NDYDATA=NYDATA+1) 
      PARAMETER (NNDYDATA=NYDATA+2) 
      PARAMETER (NZDATA=NYDATA+NCSIZE) 
      PARAMETER (NDZDATA=NZDATA+1) 
      PARAMETER (NNDZDATA=NZDATA+2) 
      PARAMETER (NPDATA=NSDATA+19) 
      PARAMETER (NLDATA=NPDATA+1) 
      PARAMETER (NMDATA=NLDATA+1) 
      PARAMETER (NBGDAT=NMDATA+1) 
      PARAMETER (NENDAT=NBGDAT+1) 
      EQUIVALENCE (IBTYPE,ISETD(NBTYPE))
      EQUIVALENCE (NINCR0,ISETD(NINDAT))
      EQUIVALENCE (NINCR1,ISETD(NINDAT+1))
      EQUIVALENCE (NINCR2,ISETD(NINDAT+2))
      EQUIVALENCE (I7,ISETD(NSDATA))
      EQUIVALENCE (I1,ISETD(NXDATA))
      EQUIVALENCE (I4,ISETD(NDXDATA))
      EQUIVALENCE (I2,ISETD(NYDATA))
      EQUIVALENCE (I5,ISETD(NDYDATA))
      EQUIVALENCE (I3,ISETD(NZDATA))
      EQUIVALENCE (I6,ISETD(NDZDATA))
      EQUIVALENCE (I_NDX,ISETD(NNDXDATA))
      EQUIVALENCE (I_NDY,ISETD(NNDYDATA))
      EQUIVALENCE (I_NDZ,ISETD(NNDZDATA))
      EQUIVALENCE (NP,ISETD(NPDATA))
      EQUIVALENCE (NL,ISETD(NLDATA))
      EQUIVALENCE (IM,ISETD(NMDATA))
      EQUIVALENCE (IBGDAT,ISETD(NBGDAT))
      EQUIVALENCE (IENDAT,ISETD(NENDAT))
      PARAMETER (T=.TRUE.)
      PARAMETER (F=.FALSE.)
      INTEGER I,J
      INTEGER IFL(19)
      INTEGER REMAIN_VAR 
      PARAMETER (REMAIN_VAR=19-5) 
      INTEGER ITTX_CYCLE(7)
      LOGICAL RFLAGS(200)
      DATA ITTX_CYCLE/2112,3776,1664,3008,1280,3328,768/
      DATA IFL(N_XDATA ) /1/
      DATA IFL(N_YDATA ) /2/
      DATA IFL(N_DXDATA) /3/
      DATA IFL(N_DYDATA) /4/
      DATA IFL(N_SYMBOL) /5/
      DATA RFLAGS/  T,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,T,T, T,T,F,F,T,
     *F,F,F,F,F, F,T,T,T,T,T,T,F,F,T, T,T,T,T,T,T,T,T,T,T, T,T,F,F,F,F,F
     *,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,
     *F,F, F,T,F,T,F,F,T,T,F,T, F,F,F,F,T,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F
     *, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F
     *,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F, F,F,
     *F,F,F,F,F,F,F,F, F,F,F,F,F,F,F,F,F,F/
      DO 10011 I=1,200
      DFLAGS(I)=RFLAGS(I)
10011 CONTINUE
10012 CONTINUE
      DO 10021 I=62,70
      FLAGS(I)=DFLAGS(I)
10021 CONTINUE
10022 CONTINUE
      DO 10031 I=1,19
      IFLDDF(I)=IFL(I)
10031 CONTINUE
10032 CONTINUE
      N_CYCLE=5
      DO 10041 I=1,MAX_CYCLE
      ITX_CYCLE(I)=ITTX_CYCLE(MIN(I,7))
      SYM_CYCLE(I)=ICHAR('O')+256*(ICHAR('0')+MIN(9,I-1))
10041 CONTINUE
10042 CONTINUE
      DGRDTYP=0
      DGRDTEX=0
      DGRDSYM=12367.
      DGRDSIZ=2.0
      DSHADOWTYP=0
      DSHADOWTEX=0
      DOUTTEX=256
      IDTXSEC=64
      IDAXTEX=256
      DTITEX=256
      DLABTEX=256
      DTICTEX=0
      DSYMBOL=0.
      DRADANG=0.0174532925
      DTIKFAC=3.0
      DEYESEP=0.
      DEYEDIS=35.
      DSCRD=-18.
      DO 10051 I=1,3
      DGRDIR(I)=0
      DSYDIR(I)=0
      DSCREV(I)=.false.
      DTIKSIZ(I)=0.1
      DBARBRK(I)=0
      DBARSIZ(I)=0.1
      DVERTCL(I)=0.
      DEYEDIR(I)=0.
      DVUECEN(I)=-77777.
      DORAXES(I)=0.
      DAXANG(I)=720.0
      DNONLN(I)=-1
      DNXYZ1(I)=0
      DNXYZ2(I)=0
      DLBLCHR(I)=6
10051 CONTINUE
10052 CONTINUE
      DSYDIR(2)=-1
      DTTHETA=30.
      DTPHI=60.
      DO 10061 J=1,2
      DO 10071 I=1,3
      DCIRSIZ(J,I)=1.0
10071 CONTINUE
10072 CONTINUE
10061 CONTINUE
10062 CONTINUE
      DTITSIZ=2.0
      DLBLSIZ=2.0
      DO 10081 I=1,19
      DFACTXY(I)=1.
10081 CONTINUE
10082 CONTINUE
      DSCLPRM(1,1)=10.
      DSCLPRM(1,2)=10.
      DSCLPRM(1,3)=10.
      DO 10091 I=1,4
      DFRELBL(I)=1.
10091 CONTINUE
10092 CONTINUE
      DTITLIN(1)=1.2
      DTITLIN(2)=2.0
      DTITLIN(3)=1.2
      DTITLIN(4)=1.2
      DTITFAC(1)=1.0
      DTITFAC(2)=1.0
      DTITFAC(3)=1.0
      DTITFAC(4)=1.5
      DO 10101 I=1,4
      DTITMAR(I)=0.025
10101 CONTINUE
10102 CONTINUE
      DTITINX=2.
      LINTXF=4
      LINWDF=2
      LINCLF=1
      DO 10111 J=1,30
      NPATRN(J)=0
      DNPATRN(J)=0
10111 CONTINUE
10112 CONTINUE
      DPATSZ=0.1
      DASIZE=2.0
      DAFLARE=0.5
      END
      SUBROUTINE T2CRMF(XVALUE,W,D,TEXT,IFIRST,ILAST)
      INTEGER W,D
      REAL XVALUE
      CHARACTER*(*) TEXT
      DOUBLE PRECISION DFIVE,DTENTH,DTENM5,DPOWER,DPART,TENPWR(6)
      CHARACTER*1 DIGIT(10)
      DATA DFIVE/5.0D0/,DTENTH/0.1D0/,DTENM5/1.D-5/
      DATA TENPWR(1)/1.D0/,TENPWR(2)/1.D1/,TENPWR(3)/1.D2/  ,TENPWR(4)/1
     *.D3/,TENPWR(5)/1.D4/,TENPWR(6)/1.D5/
      DATA DIGIT/'0','1','2','3','4','5','6','7','8','9'/
      ICOL=0
      PART=ABS(XVALUE)
      DPART=PART
      IABSD = IABS(D)
      IABSW = IABS(W)
      IF (IABSW .gt. LEN(TEXT)) GOTO 10120
      LOG=0
      IF (PART.NE.0.) THEN
      IF (D.GE.0 .AND. PART.LT.10.) THEN
      CONTINUE
      ELSEIF (D.LT.0 .AND. PART.LT.10. .AND. PART.GE.1.) THEN
      CONTINUE
      ELSE
      AL1=ALOG10(PART)
      LOG=AL1
      AL2=LOG
      IF (AL2.GT.AL1) LOG=LOG-1
      IOVER5=LOG/5
      I=5*IOVER5-LOG
      IF (I.LT.0) THEN
      I=I+5
      IOVER5=IOVER5+1
      ENDIF
      DPART=DPART*TENPWR(I+1)
      IF (IOVER5.NE.0) THEN
      IF (IOVER5.LT.0) THEN
      IOVER5=-IOVER5
      DO 10131 I=1,IOVER5
      DPART=DPART*TENPWR(6)
10131 CONTINUE
10132 CONTINUE
      ELSE
      DO 10141 I=1,IOVER5
      DPART=DPART*DTENM5
10141 CONTINUE
10142 CONTINUE
      ENDIF
      ENDIF
      ENDIF
      I=IABSD+1
      IF (D.GE.0) I=I+LOG
      IOVER5=I/5
      I=5*IOVER5-I
      IF (I.LT.0) THEN
      I=I+5
      IOVER5=IOVER5+1
      ENDIF
      DPOWER=DFIVE*TENPWR(I+1)
      DO 10151 I=1,IOVER5
      DPOWER=DPOWER*DTENM5
10151 CONTINUE
10152 CONTINUE
      DPART=DPART+DPOWER
      IF (DPART.GE.TENPWR(2)) THEN
      LOG=LOG+1
      DPART=DPART*DTENTH
      ENDIF
      ENDIF
      IWHOLE=2
      IF (D.GE.0 .AND. LOG.GT.0) IWHOLE=LOG+2
      LEAD=IABSW-IWHOLE-IABSD
      IF (D.LT.0) LEAD=LEAD-4
      IF (XVALUE.LT.0.) LEAD=LEAD-1
      IF (W.lt.0) LEAD=0
      IF (LEAD.LT.0) GO TO 10120
      IFIRST=LEAD+1
      IF (LEAD.GT.0) THEN
      TEXT(1:LEAD)=' '
      ICOL=LEAD
      ENDIF
      IF (XVALUE.LT.0.) THEN
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)='-'
      ENDIF
      N=IWHOLE+IABSD
      DO 10161 I=1,N
      IF (I.EQ.IWHOLE) THEN
      ILAST=ICOL
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)='.'
      ELSE
      J=DPART
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)=DIGIT(J+1)
      DPOWER=J
      DPART=(DPART-DPOWER)*TENPWR(2)
      IF (J.NE.0) ILAST=ICOL
      ENDIF
10161 CONTINUE
10162 CONTINUE
      IF (D.LT.0 .AND. XVALUE.NE.0.) THEN
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)='E'
      IF (LOG.LT.0) THEN
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)='-'
      ENDIF
      LOG = IABS(LOG)
      J=LOG/10
      IF(J.gt.0) THEN
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)=DIGIT(J+1)
      ENDIF
      J=MOD(LOG,10)
      ICOL=ICOL+1
      TEXT(ICOL:ICOL)=DIGIT(J+1)
      ILAST=ICOL
      ENDIF
      IF (ICOL.lt.IABSW) TEXT(ICOL+1:IABSW)=' '
      RETURN
10120 CONTINUE
      IFIRST=1
      ILAST=MIN(6,LEN(TEXT))
      TEXT='*******************'
      END
      SUBROUTINE T2ERR(INFOIN,CARDIN,MESSAG,IFLAG)
      IMPLICIT NONE
      INTEGER INFOIN(10),IFLAG,JFLAG
      CHARACTER*(*) CARDIN,MESSAG
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      CHARACTER*80 PRMP1, PRMP2
      INTEGER NPRMP1, NPRMP2
      COMMON /T2PRMP/NPRMP1, PRMP1, NPRMP2, PRMP2
      LOGICAL INTRAC,LERR
      INTEGER IPASS,I,IMIN,IMAX,J,JMIN,JMAX,JSIZ,MAXCR
      INTEGER LENGTH,FILE,MESMAX,IFIL
      INTEGER IEROUT(3),T2BTRIM
      JFLAG=ABS(IFLAG)
      LERR=.false.
      LENGTH=MIN(LEN(CARDIN),INFOIN(1))
      MAXCR=1
      DO 10171 I=1,LENGTH
      IF(CARDIN(I:I).ne.' ') MAXCR=I
10171 CONTINUE
10172 CONTINUE
      LENGTH=MAXCR
      IPASS=0
      IF (OUTFIL.gt.0) THEN
      IPASS=IPASS+1
      IEROUT(IPASS)=OUTFIL
      ENDIF
      MESMAX=1
      IF (JFLAG.le.5) THEN
      IF (JFLAG.eq.5.and.INTERP.eq.7) RETURN
      IF (ERRFIL.ne.OUTFIL .and. ERRFIL.gt.0) THEN
      IPASS=IPASS+1
      IEROUT(IPASS)=ERRFIL
      ENDIF
      IF (ERRFIL.ne.86.and.INTRAC(I) ) THEN
      IPASS=IPASS+1
      IEROUT(IPASS)=86
      ENDIF
      MESMAX=T2BTRIM(MESSAG)
      IF (MESMAX.gt.1) THEN
      IF (IFLAG.lt.0) CALL T2SQEZ(MESSAG,MESMAX)
      IF (INDEX(MESSAG,'*** ERROR').gt.0) LERR=.true.
      ENDIF
      ENDIF
      DO 10181 IFIL=1,IPASS
      FILE=IEROUT(IFIL)
      IF (FILE.eq.86) FLAGS(58)=.true.
      IF (MESSAG(1:MESMAX).ne.' ') THEN
      WRITE(FILE,*,ERR=10190)' ',MESSAG(1:MESMAX)
      IF(FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      ENDIF
      IF(JFLAG.eq.5) THEN
      GO TO (10200,10210,10220,10220,10230,10240, 10250,10260,10250),INT
     *ERP
10210 CONTINUE
      WRITE(FILE,*,ERR=10190)' *** ERROR *** ???'
      GOTO 10270
10260 CONTINUE
      IMIN=INFOIN(5)
      IMAX=MAX(IMIN,INFOIN(3))
      WRITE(FILE,*,ERR=10190) ' *** WARNING *** ', CARDIN(IMIN:IMAX),' M
     *atches ', STRNG(1:NSTRNG),' First used.'
      GO TO 10270
10200 CONTINUE
      WRITE(FILE,*,ERR=10190)  ' *** ERROR *** More information expected
     * on this line.'
      LERR=.true.
      GO TO 10270
10240 CONTINUE
10230 CONTINUE
10220 CONTINUE
10250 CONTINUE
      WRITE(FILE,*,ERR=10190)  ' *** ERROR *** Unrecognized input'
      LERR=.true.
10270 CONTINUE
      IF(FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      ENDIF
      GO TO (10280,10290,10280,10300,10300,10310),JFLAG
10310 CONTINUE
      IF (INFOIN(10).NE.0) GO TO 10280
10290 CONTINUE
      INFOIN(10)=1
      WRITE (FILE,*,ERR=10190) INFOIN(7),' ',CARDIN(1:MAXCR)
      IF (FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      IF (JFLAG.le.5) GOTO 10320
      GO TO 10280
10300 CONTINUE
      IF (NSTRNG.GT.0) THEN
      WRITE(FILE,*,ERR=10190)' * "'//STRNG(1:NSTRNG)//'"'
      IF(FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      ENDIF
      DO 10331 IMIN=1,MAXCR,77
      IMAX=MIN(IMIN+76,MAXCR)
      JMIN=INFOIN(5)
      JMAX=MIN(LENGTH,INFOIN(3))
      IF( JMIN .gt. IMAX .or. JMAX.lt.IMIN) THEN
      JSIZ=0
      ELSE
      JMIN=MIN(MAX(JMIN,IMIN),IMAX)
      JMAX=MIN(MAX(JMAX,IMIN),IMAX)
      JSIZ=JMAX-JMIN+1
      JMIN=JMIN-IMIN+1
      ENDIF
      WRITE (FILE,*,ERR=10190) ' * ',CARDIN(IMIN:IMAX)
      IF(FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      IF(JSIZ.gt.0) THEN
      WRITE(FILE,*,ERR=10190)  ' *',(' ',J=1,JMIN),('-',J=1,JSIZ)
      IF(FILE.le.NINMAX) NINP(FILE)=NINP(FILE)+1
      ENDIF
10331 CONTINUE
10332 CONTINUE
10320 CONTINUE
      CALL T2TRCE(FILE)
10280 CONTINUE
10190 CONTINUE
10181 CONTINUE
10182 CONTINUE
      IF(JFLAG.le.5) THEN
      IF (FLAGS(18).and. LERR) CALL TRACE
      IF (FLAGS(26)) CALL T2PAUS
      ENDIF
      FLAGS(23)=FLAGS(23).or.LERR
      END
      SUBROUTINE TRACE
      IMPLICIT NONE
      END
      SUBROUTINE T2STOP(STR)
      CHARACTER*(*) STR
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      CHARACTER*128 STRX
      NSTR = LEN(STR) 
      STRX = '*** FATAL *** '//STR
      CALL T2ERR(0,' ',STRX(:NSTR+14),3)
      CALL T2ERR(0,' ','*** Contact your system manager ***',3)
      CALL TRACE
      PAUSE
      STOP
      END
      SUBROUTINE T2REST
      IMPLICIT NONE
      INTEGER I,J,K
      REAL DUM
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL HNONE
      LOGICAL DFLAGS(200),DSCREV(3)
      COMMON /T2FLGD/DFLAGS,DSCREV
      REAL DTITLIN(4), DTITFAC(4), DTITMAR(4)
      INTEGER DGRDTYP, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DSHADOWTYP,DS
     *HADOWTEX, IFLDDF(19), NDDIMNS, IDTXPRI, IDTXSEC, LINCLF, LINTXF,
     * LINWDF, DNONLN(3), DNXYZ1(3), DNXYZ2(3), DLABTEX, DTICTEX, DNPAT
     *RN(30), DLBLCHR(3), ND_CYCLE, IDTX_CYCLE(MAX_CYCLE)
      REAL DSYM_CYCLE(MAX_CYCLE)
      REAL DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ(2,3), DASIZE, DAFLARE, D
     *SMSZDF, DORAXES(3), DEYEDIR(3), DVUEDIR(3), DVUECEN(3), DVERTCL(3
     *), DEYESEP, DSCRD, DSCRZ, DEYEDIS, DEYEPNT(3), DBARSIZ(3), DBARBR
     *K(3), DTIKSIZ(3), DXYZBS(3), DTTHETA, DTPHI, DFRELBL(4), DPATRN(2
     *0,30), DSCLPRM(10,3), DWINDOW(4), DSCREEN(2), DSYMBOL, DNOSYMB, 
     *DAXANG(3), DLBLSIZ, DSYMSIZ, DXYZLIM(3,2), DFACTXY(19), DRADANG,
     * DDSCAL, DPATSZ, DTITINX, DTIKFAC, DSYDIR(3), DGRDIR(3)
      COMMON /T2COMD/ DTITSIZ, DGRDSYM, DGRDSIZ, DCIRSIZ, DASIZE, DAFLA
     *RE, DSMSZDF, DORAXES, DEYEDIR, DVUEDIR, DVUECEN, DVERTCL, DEYESE
     *P, DSCRD, DSCRZ, DEYEDIS, DEYEPNT, DBARSIZ, DTIKSIZ, DXYZBS, DTTH
     *ETA, DTPHI, DFRELBL, DNPATRN, DPATRN, DSCLPRM, DWINDOW, DSCREEN,
     * DSYMBOL, DNOSYMB, DAXANG, DLBLSIZ, DSYMSIZ, DXYZLIM, DGRDTYP, D
     *FACTXY, IFLDDF, NDDIMNS, DGRDTEX, DOUTTEX, IDAXTEX, DTITEX, DRADA
     *NG, DDSCAL, DNONLN, DNXYZ1, DNXYZ2, LINCLF, LINTXF, LINWDF, DLABT
     *EX, DTICTEX, DPATSZ, IDTXPRI, IDTXSEC, DTITLIN, DTITINX, DLBLCHR,
     * DTITFAC, DTITMAR, DTIKFAC, DSYDIR, DGRDIR, ND_CYCLE, IDTX_CYCLE,
     * DSYM_CYCLE, DBARBRK,  DSHADOWTYP,DSHADOWTEX
      DATA HNONE /-666.666/
      IBLINK=0
      CALL TXXOPT(10,IBLINK,DUM,I)
      IERASE=0
      CALL TXXOPT(11,IERASE,DUM,I)
      DO 10341 I=2,13
      FLAGS(I)=DFLAGS(I)
10341 CONTINUE
10342 CONTINUE
      DO 10351 I=19,22
      FLAGS(I)=DFLAGS(I)
10351 CONTINUE
10352 CONTINUE
      FLAGS(27)=DFLAGS(27)
      DO 10361 I=32,52
      FLAGS(I)=DFLAGS(I)
10361 CONTINUE
10362 CONTINUE
      DO 10371 I=71,81
      FLAGS(I)=DFLAGS(I)
10371 CONTINUE
10372 CONTINUE
      DO 10381 I=84,92
      FLAGS(I)=DFLAGS(I)
10381 CONTINUE
10382 CONTINUE
      FLAGS(94)=DFLAGS(94)
      DO 10391 I=120,200
      FLAGS(I)=DFLAGS(I)
10391 CONTINUE
10392 CONTINUE
      DO 10401 I=1,3
      DO 10411 J=1,10
      SCLPRM(J,I)=DSCLPRM(J,I)
10411 CONTINUE
10412 CONTINUE
10401 CONTINUE
10402 CONTINUE
      DO 10421 I=1,3
      LSCREV(I)=DSCREV(I)
      TIKSIZ(I)=DTIKSIZ(I)
      BARBRK(I)=DBARBRK(I)
      BARSIZ(I)=DBARSIZ(I)
      LBLCHR(I)=DLBLCHR(I)
      NONLIN(I)=DNONLN(I)
      NXYZ1(I)=DNXYZ1(I)
      NXYZ2(I)=DNXYZ2(I)
      AXANG(I)=DAXANG(I)
10421 CONTINUE
10422 CONTINUE
      TIKFAC=DTIKFAC
      IF(.not.FLAGS(61)) THEN
      FLAGS(82)=DFLAGS(82)
      FLAGS(55)=DFLAGS(55)
      NDIMNS(1)=NDDIMNS
      EYESEP=DEYESEP
      EYEDIS=DEYEDIS
      SCRD=DSCRD
      DO 10431 I=1,3
      VERTCL(I)=DVERTCL(I)
      EYEDIR(I)=DEYEDIR(I)
      VUECEN(I)=DVUECEN(I)
      ORAXES(I)=DORAXES(I)
      GRDIR(I) =DGRDIR(I)
      SYDIR(I) =DSYDIR(I)
10431 CONTINUE
10432 CONTINUE
      TTHETA=DTTHETA
      TPHI=DTPHI
      ENDIF
      FLAGS(61)=.FALSE.
      FLAGS(56)=(IDIMNS.eq.3.or.NDIMNS(1).eq.3) .and. NDIMNS(1).ne.2
      MESH2D=0
      SYMBOL=DSYMBOL
      SYMSIZ=SMSZDF
      NFIELD=0
      DO 10441 I=1,19
      IFIELD(I)=IFLDDF(I)
      NFIELD=MAX(NFIELD,IFLDDF(I))
      FACTXY(I)=DFACTXY(I)
10441 CONTINUE
10442 CONTINUE
      DO 10451 I=1,MAX_CYCLE
      ITX_CYCLE(I)=IDTX_CYCLE(I)
      SYM_CYCLE(I)=DSYM_CYCLE(I)
10451 CONTINUE
10452 CONTINUE
      RADANG=DRADANG
      GRDTYP=DGRDTYP
      GRDTEX=DGRDTEX
      GRDSYM=DGRDSYM
      GRDSIZ=DGRDSIZ
      SHADOWTYP=DSHADOWTYP
      SHADOWTEX=DSHADOWTEX
      OUTTEX=DOUTTEX
      ITXPRI=IDTXPRI
      ITXSEC=IDTXSEC
      IAXTEX=IDAXTEX
      TITEX=DTITEX
      LABTEX=DLABTEX
      TICTEX=DTICTEX
      ASIZE=DASIZE
      AFLARE=DAFLARE
      TITX = SCREEN(1)*0.1
      TITY = SCREEN(2) * 0.9
      TITZ=0
      TITX1=TITX
      TITY1=TITY
      ITCNTR=0
      LTDATA=.false.
      TITCON(1)=DTITSIZ
      TITCON(2)=0
      TITCON(3)=0
      TITCON(4)=DTITINX
      TITCON(5)=0
      DO 10461 I=1,3
      ITITDT(I)=0
10461 CONTINUE
10462 CONTINUE
      DO 10471 I=1,4
      FRELBL(I)=DFRELBL(I)
      TITLIN(I)=DTITLIN(I)
      TITFAC(I)=DTITFAC(I)
      TITMAR(I)=DTITMAR(I)
10471 CONTINUE
10472 CONTINUE
      IWINLEV=1
      DO 10481 I=1,2
      WINLIM(I,1)=0
      WINLIM(I,2)=SCREEN(I)
10481 CONTINUE
10482 CONTINUE
      DO 10491 I=1,2
      DO 10501 J=1,2
      XYPART(J,I)=1.
      WINREL(J,I,1)=1
      WINABS(J,I,1)=WINLIM(J,I)
10501 CONTINUE
10502 CONTINUE
10491 CONTINUE
10492 CONTINUE
      TITINX=DTITINX
      TITSIZ=DTITSIZ
      LBLSIZ=DLBLSIZ
      LINWID = LINWDF
      LINTEX = LINTXF
      LINCOL = LINCLF
      PATSZ = DPATSZ
      IPATRN= 1
      DO 10511 I=1,2
      DO 10521 J=1,3
      NXYLIM(J,I)=0
10521 CONTINUE
10522 CONTINUE
10511 CONTINUE
10512 CONTINUE
      EXYZLIM(1,1)=HNONE
      DO 10531 I=1,3
      DO 10541 J=1,2
      CIRSIZ(J,I)=DCIRSIZ(J,I)
10541 CONTINUE
10542 CONTINUE
10531 CONTINUE
10532 CONTINUE
      DO 10551 I=1,12
      XFRM12(I)=0
      XFRM13(I)=0
      XFRM14(I)=0
      XFRM23(I)=0
      XFRM24(I)=0
10551 CONTINUE
10552 CONTINUE
      DO 10561 I=1,6
      XFRM34(I)=0
10561 CONTINUE
10562 CONTINUE
      END
      SUBROUTINE T2PNTR
      IMPLICIT NONE
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      INTEGER LISTPT,NPTMAX,NDSETS
      REAL DATBUF(10248)
      COMMON /T2XPNT/ LISTPT,NPTMAX,NDSETS,DATBUF
      IBLKTP=1
      ENTRY T2CLRS
      IF (.NOT.FLAGS(28).and.(NPOINT.gt.NDSETS.or.NMESH1.ne.0)) THEN
      CALL T2ERR(0,' ',('*** WARNING *** Unplotted data deleted'),3)
      ENDIF
      NPOINT=0
      NMESH0=1
      NMESH1=0
      NMESH2=0
      NDSETS=0
      CALL T2SETS(0)
      END
      SUBROUTINE T2SETS(IVAR)
      IMPLICIT NONE
      INTEGER IVAR(*)
      INTEGER I,J,K,L,INEW(19),New,IMIN,IMAX,ISTEP,IPOINT,ISET
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      INTEGER LISTPT,NPTMAX,NDSETS
      REAL DATBUF(10248)
      COMMON /T2XPNT/ LISTPT,NPTMAX,NDSETS,DATBUF
      REAL HNONE
      INTEGER NSETD 
      PARAMETER (NSETD=19+9)
      INTEGER ISETD(NSETD),NINCR0,NINCR1,NINCR2,IBTYPE
      INTEGER I1,I2,I3,I4,I5,I6,I7,IM,NP,NL,IENDAT,IBGDAT
      INTEGER I_NDX,I_NDY,I_NDZ
      INTEGER N_SYMBOL 
      INTEGER N_XDATA 
      INTEGER N_DXDATA 
      INTEGER N_NDXDATA 
      INTEGER N_YDATA 
      INTEGER N_DYDATA 
      INTEGER N_NDYDATA 
      INTEGER N_ZDATA 
      INTEGER N_DZDATA 
      INTEGER N_NDZDATA 
      INTEGER N_UDATA 
      INTEGER N_DUDATA 
      INTEGER N_NDUDATA 
      INTEGER N_VDATA 
      INTEGER N_DVDATA 
      INTEGER N_NDVDATA 
      INTEGER N_WDATA 
      INTEGER N_DWDATA 
      INTEGER N_NDWDATA 
      INTEGER NCMAX 
      INTEGER NCSIZE 
      INTEGER NBTYPE 
      INTEGER NINDAT 
      INTEGER NSDATA 
      INTEGER NXDATA 
      INTEGER NDXDATA 
      INTEGER NNDXDATA 
      INTEGER NYDATA 
      INTEGER NDYDATA 
      INTEGER NNDYDATA 
      INTEGER NZDATA 
      INTEGER NDZDATA 
      INTEGER NNDZDATA 
      INTEGER NPDATA 
      INTEGER NLDATA 
      INTEGER NMDATA 
      INTEGER NBGDAT 
      INTEGER NENDAT 
      PARAMETER (N_SYMBOL=1) 
      PARAMETER (N_XDATA=2) 
      PARAMETER (N_DXDATA=3) 
      PARAMETER (N_NDXDATA=4) 
      PARAMETER (N_YDATA=5) 
      PARAMETER (N_DYDATA=6) 
      PARAMETER (N_NDYDATA=7) 
      PARAMETER (N_ZDATA=8) 
      PARAMETER (N_DZDATA=9) 
      PARAMETER (N_NDZDATA=10) 
      PARAMETER (N_UDATA=11) 
      PARAMETER (N_DUDATA=12) 
      PARAMETER (N_NDUDATA=13) 
      PARAMETER (N_VDATA=14) 
      PARAMETER (N_DVDATA=15) 
      PARAMETER (N_NDVDATA=16) 
      PARAMETER (N_WDATA=17) 
      PARAMETER (N_DWDATA=18) 
      PARAMETER (N_NDWDATA=19) 
      PARAMETER (NCMAX=6) 
      PARAMETER (NCSIZE=3) 
      PARAMETER (NBTYPE=1) 
      PARAMETER (NINDAT=2) 
      PARAMETER (NSDATA=5) 
      PARAMETER (NXDATA=NSDATA+1) 
      PARAMETER (NDXDATA=NXDATA+1) 
      PARAMETER (NNDXDATA=NXDATA+2) 
      PARAMETER (NYDATA=NXDATA+NCSIZE) 
      PARAMETER (NDYDATA=NYDATA+1) 
      PARAMETER (NNDYDATA=NYDATA+2) 
      PARAMETER (NZDATA=NYDATA+NCSIZE) 
      PARAMETER (NDZDATA=NZDATA+1) 
      PARAMETER (NNDZDATA=NZDATA+2) 
      PARAMETER (NPDATA=NSDATA+19) 
      PARAMETER (NLDATA=NPDATA+1) 
      PARAMETER (NMDATA=NLDATA+1) 
      PARAMETER (NBGDAT=NMDATA+1) 
      PARAMETER (NENDAT=NBGDAT+1) 
      EQUIVALENCE (IBTYPE,ISETD(NBTYPE))
      EQUIVALENCE (NINCR0,ISETD(NINDAT))
      EQUIVALENCE (NINCR1,ISETD(NINDAT+1))
      EQUIVALENCE (NINCR2,ISETD(NINDAT+2))
      EQUIVALENCE (I7,ISETD(NSDATA))
      EQUIVALENCE (I1,ISETD(NXDATA))
      EQUIVALENCE (I4,ISETD(NDXDATA))
      EQUIVALENCE (I2,ISETD(NYDATA))
      EQUIVALENCE (I5,ISETD(NDYDATA))
      EQUIVALENCE (I3,ISETD(NZDATA))
      EQUIVALENCE (I6,ISETD(NDZDATA))
      EQUIVALENCE (I_NDX,ISETD(NNDXDATA))
      EQUIVALENCE (I_NDY,ISETD(NNDYDATA))
      EQUIVALENCE (I_NDZ,ISETD(NNDZDATA))
      EQUIVALENCE (NP,ISETD(NPDATA))
      EQUIVALENCE (NL,ISETD(NLDATA))
      EQUIVALENCE (IM,ISETD(NMDATA))
      EQUIVALENCE (IBGDAT,ISETD(NBGDAT))
      EQUIVALENCE (IENDAT,ISETD(NENDAT))
      LOGICAL LRESET
      REAL XYZ(19)
      INTEGER IBSET,IBCLR
      LOGICAL T2_VIRT,DMMY
      DATA HNONE /-666.666/
      DATDAT(1,1)=HNONE
      MESH2D=0
      MESH1=0
      MESH2=0
      MESH3=0
      NMESH0=1
      NMESH1=0
      NMESH2=0
      IF (NDSETS.eq.0) IVRPTR(12)=LISTPT
      DATBUF(1)=HNONE
      LRESET=.false.
      NEW=MIN(IVAR(1),19)
      IPOINT=0
      IF (NEW.ne.0) THEN
      DO 10571 I=1,NEW
      INEW(I)=IVAR(I+1)
10571 CONTINUE
10572 CONTINUE
      IF (NEW .eq. NINCR) THEN
      DO 10581 I=1,NINCR
      IF (INEW(I).ne.IVARBL(I)) LRESET=.true.
10581 CONTINUE
10582 CONTINUE
      ELSE
      LRESET=.true.
      ENDIF
      ENDIF
      IF (LRESET) THEN
      DO 10591 ISET=1,NDSETS
      CALL T2GDSET(ISET,1, 2 147 483 647  ,1, 2 147 483 647,ISETD,HNONE,
     *'*')
      IF (IBLKTP.eq.1) IPOINT=IPOINT+NP
10591 CONTINUE
10592 CONTINUE
      IF (IPOINT.gt.0) THEN
      IPOINT=IPOINT*(NEW-NINCR)
      IF (IPOINT.gt.0) THEN
C     CALL T2_VIRT(IPOINT)
      DMMY=T2_VIRT(IPOINT)	! for unix-fortran
      ENDIF
      IF (LISTPT+IPOINT.gt.NPTMAX) THEN
      CALL T2ERR(0,' ','*** ERROR *** Too much data to modify storage',3
     *)
      RETURN
      ENDIF
      L=0
      DO 10601 I=1,NINCR
      L=IBSET(L,IVARBL(I))
10601 CONTINUE
10602 CONTINUE
      DO 10611 I=1,NEW
      L=IBCLR(L,INEW(I))
10611 CONTINUE
10612 CONTINUE
      IF (L.ne.0) CALL T2ERR(0,' ','*** WARNING *** Some data coordinate
     *s will be lost',3)
      DO 10621 I=1,8
      XYZ(I)=0
10621 CONTINUE
10622 CONTINUE
      DO 10631 ISET=1,NDSETS
      CALL T2GDSET(ISET,1, 2 147 483 647  ,1, 2 147 483 647,ISETD,HNONE,
     *'*')
      IF (IBLKTP.EQ.1) THEN
      IPOINT=(NEW-NINCR)*(NP)
      NP=NP-1
      IF (IPOINT.gt.0) THEN
      DO 10641 I=IVRPTR(12)-1,IENDAT+1,-1
      DATBUF(I+IPOINT)=DATBUF(I)
10641 CONTINUE
10642 CONTINUE
      IMIN=NP
      IMAX=0
      ISTEP=-1
      ELSE
      IMIN=0
      IMAX=NP
      ISTEP=1
      ENDIF
      DO 10651 I=IMIN,IMAX,ISTEP
      K=IM+I*NINCR
      DO 10661 J=1,NINCR
      XYZ(IVARBL(J))=DATBUF(K)
      K=K+1
10661 CONTINUE
10662 CONTINUE
      K=IM+I*NEW
      DO 10671 J=1,NEW
      DATBUF(K)=XYZ(INEW(J))
      K=K+1
10671 CONTINUE
10672 CONTINUE
10651 CONTINUE
10652 CONTINUE
      IF (IPOINT.lt.0) THEN
      DO 10681 I=IENDAT+1,IVRPTR(12)-1
      DATBUF(I+IPOINT)=DATBUF(I)
10681 CONTINUE
10682 CONTINUE
      ENDIF
      IVRPTR(12)=IVRPTR(12)+IPOINT
      IENDAT=IENDAT+IPOINT
      DATBUF(IBGDAT+2)=DATBUF(IBGDAT+2)+IPOINT
      ENDIF
10631 CONTINUE
10632 CONTINUE
      ENDIF
      NINCR=NEW
      NDIMNS(3)=0
      DO 10691 I=1,19
      IVPTR(i)=0
10691 CONTINUE
10692 CONTINUE
      DO 10701 I=1,NINCR
      IVARBL(I)=INEW(I)
      IF (IVARBL(I) .le. N_NDZDATA) NDIMNS(3)=MAX(NDIMNS(3),(IVARBL(I)-N
     *_XDATA)/NCSIZE+1)
10701 CONTINUE
10702 CONTINUE
      DO 10711 I=1,NINCR
      IVPTR(IVARBL(I))=I
10711 CONTINUE
10712 CONTINUE
      ENDIF
      CALL T2GDSET(NDSETS,1, 2 147 483 647  ,1, 2 147 483 647,ISETD,HNON
     *E,'*')
      IVRPTR(14)=LISTPT
      IF(.not.FLAGS(75)) THEN
      FLAGS(56)=(IDIMNS.eq.3.or.NDIMNS(1).eq.3) .and. NDIMNS(1).ne.2
      ENDIF
      FLAGS(28)=.false.
      END
      SUBROUTINE T2TRCE(IFILE)
      IMPLICIT NONE
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      INTEGER I,J,JMAX,IFILE,T2BTRIM
      IF(IFILE.le.0) RETURN
      DO 10721 I=INPFIL,10,-1
      INQUIRE(UNIT=I,NAME=OUTSTR)
      J=0
      IF(I.le.NINMAX) J=NINP(I)
      JMAX=T2BTRIM(OUTSTR)
      WRITE(IFILE,*,ERR=10190)' * Line=',J, ' File=','"'//OUTSTR(:JMAX)/
     */'"'
      IF (IFILE.le.NINMAX) NINP(IFILE)=NINP(IFILE)+1
10721 CONTINUE
10722 CONTINUE
10190 CONTINUE
      END
      SUBROUTINE T2_CONCEAL_PASSWORD(FILE,N_FILE)
      IMPLICIT NONE
      CHARACTER*(*) FILE
      INTEGER IMIN,IMAX,I,N_FILE,T2BTRIM
      IF (N_FILE .le. 0 .or. N_FILE .gt. LEN(FILE)) N_FILE=T2BTRIM(FILE)
     *
      END
