C        MORTRAN 2.79 (BRACKETED KEYWORD MACROS OF 09/28/81)          
      SUBROUTINE T2TABL(XVALS,YVALS,ZVALS,NP,INCRMT,ITXTUR,SIZE,TLIM, XE
     *RRS,YERRS,ZERRS,OFFSET,IOPT)
      INTEGER INCRMT,NP,ITXTUR,IOFFSET
      REAL XVALS(INCRMT,*),YVALS(INCRMT,*),ZVALS(INCRMT,*), XERRS(INCRMT
     *,*),YERRS(INCRMT,*),ZERRS(INCRMT,*), TLIM(3,2),SIZE,OFFSET,TOFF
      INTEGER I,J,K
      REAL XYZV(3),XY(2),XY2(2,2),WIDTH
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL HNONE
      CHARACTER*20 TEXT,CASE
      LOGICAL LEXIST(3),T2SCIS,LCYCLE,LTOP,LEDGE,LABSOLUTE,LDATA,LOFFSET
     *, LVALUE,LLIM,LOKAY
      INTEGER IAND
      DATA HNONE /-666.666/
      LCYCLE=IAND(ITXTUR,4) .ne. 0
      CALL T2AXES
      IF (.not.FLAGS(75)) RETURN
      FLAGS(28) = .TRUE.
      CALL T2CWTS(JTYPE,ITXSAV)
      CALL TXSDEF
      CALL TXSCIS(2)
      LOFFSET=OFFSET .ne. HNONE
      LTOP = IAND(IOPT,1) .ne. 0
      LVALUE=IAND(IOPT,8) .ne. 0
      LDATA= LOFFSET .and. IAND(IOPT,2) .ne. 0
      LABSOLUTE= LOFFSET .and. IAND(IOPT,4) .ne. 0
      IF ( LVALUE ) LTOP= .not. LTOP
      IF (SIZE.ne.0 ) THEN
      MINPAS=1
      SYSIZ=SIZE
      ELSE
      MINPAS=0
      SYSIZ=SYMSIZ
      ENDIF
      LEXIST(1)=XVALS(1,1).NE.HNONE
      LEXIST(2)=YVALS(1,1).NE.HNONE
      LEXIST(3)=ZVALS(1,1).NE.HNONE
      IDEP=1
      DO 10011 I=1,3
      XYZV(I)=0
      IF(LEXIST(I)) IDEP=I
10011 CONTINUE
10012 CONTINUE
      LLIM=TLIM(1,1) .ne. HNONE
      WIDTH=LBLSIZ/10.
      X0=1.0E35
      LEDGE = XOR ( LTOP, LSCREV(IDEP) )
      DO 10021 NPASS=MINPAS,1
      SCHSIZ=SYSIZ*REDUCE(2)/10
      IF (LOFFSET) THEN
      TOFF=OFFSET
      ELSE
      TOFF=3*ABS(TIKFAC*TIKSIZ(1))+ABS(SCHSIZ)
      ENDIF
      IF (LTOP) TOFF=-(TOFF)
      DO 10031 N=1,NP
      IF (LTRAP) goto 10040
      IF (LEXIST(1)) XYZV(1)=XVALS(1,N)
      IF (LEXIST(2)) XYZV(2)=YVALS(1,N)
      IF (LEXIST(3)) XYZV(3)=ZVALS(1,N)
      LOKAY=.TRUE.
      IF (LLIM) THEN
      DO 10051 I=1,IDEP
      IF (LOKAY .and. LEXIST(I)) LOKAY= XYZV(I).GE.TLIM(I,1) .and.XYZV(I
     *) .LE.TLIM(I,2)
10051 CONTINUE
10052 CONTINUE
      ELSE
      DO 10061 I=1,IDEP
      IF (ABS(XYZV(1)).ge.1.0E35) LOKAY=.false.
10061 CONTINUE
10062 CONTINUE
      ENDIF
      IF(.not.LOKAY)GOTO 10031
      VAL=XYZV(IDEP)
      IF (.not. LVALUE ) THEN
      IF (LEDGE) THEN
      XYZV(IDEP)=XYZLIM(IDEP,2)
      ELSE
      XYZV(IDEP)=XYZLIM(IDEP,1)
      ENDIF
      ENDIF
      IF (LDATA) THEN
      XYZV(IDEP)=XYZV(IDEP)+TOFF
      IF (LABSOLUTE) XYZV(IDEP)=TOFF
      ENDIF
      CALL T2XFRM(3,1,XYZV,NONLIN,XFRM13,2,XY)
      IF (.not. LDATA) THEN
      XY(2)=XY(2)+TOFF
      IF (LABSOLUTE) XY(2)=TOFF
      ENDIF
      CALL T2XFRM(2,1,XY,LINEAR,XFRM34,2,XY2)
      IF (T2SCIS(XY2)) THEN
      IF (NPASS.gt.0) THEN
      CALL T2TLAB(9,VAL,BASE,8,1, TEXT,NTEXT,CASE,NCASE,IFIRST)
      IF (.not. LTOP) THEN
      XY(2)=XY(2)+  ABS(TXXCSZ(TEXT(1:NTEXT),CASE(1:NTEXT),SCHSIZ))
      ENDIF
      CALL T2XFRM(2,1,XY,LINEAR,XFRM34,2,XY2)
      CALL TXTEXT(XY2(1,1),XY2(2,1), SYSIZ,-90., TEXT(1:NTEXT), CASE(1:N
     *TEXT))
      ELSE
      IF (ABS(X0).lt.1.0E35 .and. XY(1).ne.X0) WIDTH=MIN(WIDTH,ABS(XY(1)
     *-X0))
      X0=XY(1)
      ENDIF
      ENDIF
10031 CONTINUE
10032 CONTINUE
      IF (SIZE.eq.0) THEN
      WIDTH=MAX(WIDTH,0.02)
      SYSIZ=SIGN(7*WIDTH,LBLSIZ)
      ENDIF
10021 CONTINUE
10022 CONTINUE
10040 CONTINUE
      CALL TXSCIS(1)
      CALL T2CWTS(ITXSAV,IDUM)
      CALL T2TCKS(0)
      END
      SUBROUTINE T23TBL(ARRAY,NDIM0,NDIM1,NDIM2,N1,N2,N3,N4,SIZE,ITXTUR,
     *TLIM)
      INTEGER NDIM0,NDIM1,NDIM2
      REAL ARRAY(NDIM0,NDIM1,NDIM2+1),SIZE,TLIM(3,2)
      REAL XYZ(3),XY(2),XYZ2(3,2),XY2(2,2),ENCHAR
      LOGICAL LTEST,LOVER,T2SCIS,LCYCLE,LLOG,LLIMIT
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL ANGSAV(3)
      CHARACTER*30 TEXT,CASE
      CHARACTER*10 CXYZ(3)
      DATA TEXT,CASE/' ',' '/
      DATA CXYZ/'X,CEN,DATA','Y,CEN,DATA','Z,CEN,DATA'/
      IF (NDIM1.lt.2.or.NDIM2.lt.2) THEN
      CALL T2ERR(0,' ',('*** ERROR *** Bad array in T23TBL'),3)
      RETURN
      ENDIF
      DO 10071 I=1,3
      ANGSAV(I)=AXANG(I)
      J=MESH1
      IF (I.eq.MESH1) J=MESH2
      IF (J .eq. I+1) THEN
      AXANG(I)=0
      ELSE
      AXANG(I)=90.
      ENDIF
10071 CONTINUE
10072 CONTINUE
      IF (.NOT.FLAGS(75)) FLAGS(56)=NDIMNS(1).eq.3
      CALL T23LIM(ARRAY,NDIM0,NDIM1,NDIM2)
      CALL T2AXES
      MINAX=1
      IF (.not.FLAGS(75)) RETURN
      FLAGS(28) = .TRUE.
      XMIN=T2MSHX(ARRAY,NDIM0,NDIM1,NDIM2,0)
      XMAX=T2MSHX(ARRAY,NDIM0,NDIM1,NDIM2,NDIM1)
      YMIN=T2MSHY(ARRAY,NDIM0,NDIM1,NDIM2,0)
      YMAX=T2MSHY(ARRAY,NDIM0,NDIM1,NDIM2,NDIM2)
      WIDTH=(XMAX-XMIN)/(NDIM1-1)
      DEPTH=(YMAX-YMIN)/(NDIM2-1)
      DO 10081 I=1,3
      DO 10091 J=1,2
      XYZ2(I,J)=(XYZLIM(I,1)+XYZLIM(I,2))/2
10091 CONTINUE
10092 CONTINUE
10081 CONTINUE
10082 CONTINUE
      XYZ2(MESH1,1)=XYZ2(MESH1,1)+WIDTH
      XYZ2(MESH2,1)=XYZ2(MESH2,1)+DEPTH
      CALL T2XFRM(3,2,XYZ2,LINEAR,XFRM13,2,XY2)
      CALL TXSCIS(2)
      CALL T2CWTS(IAXTEX,ITXSAV)
      CALL T2CWTS(LABTEX,IDUM)
      CALL T2CWTS(ITXTUR,IDUM)
      CALL TXSDEF
      LCYCLE=IAND(ITXTUR,4) .ne. 0
      IF (LCYCLE) THEN
      ZMIN=XYZLIM(MESH3,1)
      ZMAX=XYZLIM(MESH3,2)
      IF (LLOG.and.ZMIN.ne.0.and.ZMAX.ne.0) THEN
      ZMAX=ALOG10(ABS(ZMAX))
      ZMIN=ALOG10(ABS(ZMIN))
      ENDIF
      ZDIFF=ZMAX-ZMIN
      IF (ZDIFF.eq.0) ZDIFF=1.0
      ENDIF
      LLIMIT=TLIM(1,1) .ne. HNONE
      ENCHAR=1
      BASE=SCLPRM(1,MESH3)
      IF (SIZE.ne.0) THEN
      MINPAS=1
      ELSE
      MINPAS=0
      ENDIF
      SCHSIZ=SIGN(1.0,LBLSIZ)
      MAJMIN=2
      MAJMAX=NDIM1
      MINMIN=2
      MINMAX=NDIM2
      IF(N1.gt.0) MAJMIN=MIN(NDIM1,N1+1)
      IF(N2.gt.0) MAJMAX=MIN(NDIM1,N2+1)
      IF(N3.gt.0) MINMIN=MIN(NDIM2,N3+1)
      IF(N4.gt.0) MINMAX=MIN(NDIM2,N4+1)
      DO 10101 NPASS=MINPAS,1
      IF (NPASS.eq.1) THEN
      SYSIZ=0
      IF (SIZE.ne.0) THEN
      SYSIZ=SIZE
      ELSE
      SYSIZ=10*MIN(0.7*ABS(XY2(2,2)-XY2(2,1)), ABS(XY2(1,2)-XY2(1,1))/EN
     *CHAR)
      SYSIZ=SIGN(SYSIZ,LBLSIZ)
      IF (ABS(SYSIZ).gt.ABS(LBLSIZ)) SYSIZ=LBLSIZ
      ENDIF
      IF (SYSIZ.eq.0) SYSIZ=LBLSIZ
      SCHSIZ=SYSIZ*REDUCE(2)/10
      ENDIF
      DO 10111 IY=MINMIN,MINMAX
      Y1=ARRAY(1,1,IY)
      IF(LLIMIT .or. (Y1.GE.TLIM(MESH2,1) .and. Y1.LE.TLIM(MESH2,2))) TH
     *EN
      XYZ(MESH2)=Y1
      DO 10121 IX=MAJMIN,MAJMAX
      X1=ARRAY(1,IX,1)
      XYZ(MESH1)=X1
      IF (LTRAP) GOTO 10130
      IF(LLIMIT .or. (X1.GE.TLIM(MESH1,1) .and. X1.LE.TLIM(MESH1,2))) TH
     *EN
      Z1=ARRAY(1,IX,IY)
      IF(LLIMIT .or. (Z1.GE.TLIM(MESH3,1).AND.Z1.LE.TLIM(MESH3,2))) THEN
     *
      XYZ(MESH3)=Z1
      IF (LCYCLE) THEN
      IF (LLOG) THEN
      IF( Z1 .ne. 0) THEN
      Z1=ALOG10(ABS(Z1))
      ELSE
      Z1=ZMIN
      ENDIF
      ENDIF
      ICYCLE=N_CYCLE*((Z1-ZMIN)/ZDIFF)+1
      ICYCLE=MAX(MIN(N_CYCLE,ICYCLE),1)
      CALL T2CWTS(ITX_CYCLE(ICYCLE),IDUM)
      CALL T2CWTS(ITXTUR,IDUM)
      CALL TXSDEF
      ENDIF
      CALL T2TLAB(9,XYZ(MESH3),BASE,8,1, TEXT,NTEXT,CASE,NCASE,IFIRST)
      T=TXXCSZ(TEXT(1:NTEXT),CASE(1:NTEXT),SCHSIZ)
      ENCHAR=MAX(ENCHAR,T+2)
      IF (NPASS.gt.0) THEN
      CALL T2XFRM(3,1,XYZ,NONLIN,XFRM13,2,XY)
      XY(1)=XY(1)-T/2
      CALL T2XFRM(2,1,XY,LINEAR,XFRM34,2,XY2)
      IF (T2SCIS(XY2)) CALL TXTEXT(XY2(1,1),XY2(2,1), SYSIZ,0., TEXT(1:N
     *TEXT), CASE(1:NTEXT))
      ENDIF
      ENDIF
      ENDIF
10121 CONTINUE
10122 CONTINUE
      ENDIF
10111 CONTINUE
10112 CONTINUE
10101 CONTINUE
10102 CONTINUE
10130 CONTINUE
      CALL T2CWTS(ITXSAV,IDUM)
      CALL TXSCIS(1)
      IF (.not.FLAGS(27).and..not.FLAGS(56)) CALL T2TCKS(0)
      END
