C        MORTRAN 2.79 (BRACKETED KEYWORD MACROS OF 09/28/81)          
      SUBROUTINE T2XFRM(NIN,NUM,VECIN,ISCAL,XFRM,NOUT,VECOUT)
      INTEGER NIN,NOUT,ISCAL(4)
      REAL VECIN(NIN,NUM),VECOUT(NOUT,NUM),XFRM(12)
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL VEC(3),VEC2(3)
      INTEGER IDAYS(12)
      DATA IDAYS/0,31,59,90,120,151,181,212,242,273,303,334/
      DO 10011 I=1,3
      VEC(I)=0
      VEC2(I)=0
10011 CONTINUE
10012 CONTINUE
      DO 10021 NPT=1,NUM
      DO 10031 I=1,NIN
      VEC(I)=VECIN(I,NPT)
10031 CONTINUE
10032 CONTINUE
      DO 10041 I=1,NIN
      IF (ISCAL(I).LT.0) then
10050 GOTO (10060,10070,10080,10090,10100,10110,10120,10130),-ISCAL(I)
10060 CONTINUE
      GOTO 10052
10070 CONTINUE
      IF (VEC(I).GT.0.) THEN
      VEC(I)=ALOG10(VEC(I))
      ELSE
      VEC(I) = -10000.
      ENDIF
      GOTO 10052
10080 CONTINUE
      IF (VEC(I).LT.0.) THEN
      VEC(I)=ALOG10(-VEC(I))
      ELSE
      VEC(I) = 10000.
      endif
      GOTO 10052
10100 CONTINUE
      T=MIN(MAX(VEC(I),-1.0E9),1.0E9)
      JYEAR = T
      IF(T.lt.JYEAR) JYEAR=JYEAR-1
      LEAPS = (JYEAR+3)/4
      PART = 1000*(T-JYEAR)-1
      VEC(I) = JYEAR*365. + PART+LEAPS
      GOTO 10052
10090 CONTINUE
      T = VEC(I)
      MONTH = T
      IF (MONTH.gt.T) MONTH=MONTH-1
      PART = 100*(T-.005-MONTH)
      JYEAR = (MONTH-1)/12
      LEAPS = (MONTH+9)/48
      MONTH = MOD(MONTH-1,12)+1
      IF (MONTH.le.0) THEN
      MONTH=MONTH+12
      JYEAR=JYEAR-1
      ENDIF
      J=JYEAR*365+IDAYS(MONTH)+LEAPS
      VEC(I) = PART+J
      GOTO 10052
10110 CONTINUE
      VEC(I)=T2FRQF((VEC(I)-SCLPRM(2,I))/SCLPRM(3,I))
      GOTO 10052
10120 CONTINUE
      CONTINUE
      GOTO 10052
10130 CONTINUE
      TEMP=VEC(I)
      VEC(I)=SIGN(ABS(TEMP)**SCLPRM(4,I),TEMP)
      GOTO 10052
10052 CONTINUE
      ELSE
      VEC(I)=TDFNCT(VECIN(I,NPT),SCLPRM(1,I))
      endif
10041 CONTINUE
10042 CONTINUE
      IF (ISCAL(4).NE.0 .AND. FLAGS(27)) then
      THET1=VEC(1)*RADANG
      RAD = VEC(2)
      IF(FLAGS(91)) THEN
      PHI1 =VEC(3)*RADANG
      VEC(1)=RAD*COS(THET1)*SIN(PHI1)
      VEC(2)=RAD*SIN(THET1)*SIN(PHI1)
      VEC(3)=RAD*COS(PHI1)
      ELSE
      VEC(1)=RAD*COS(THET1)
      VEC(2)=RAD*SIN(THET1)
      endif
      endif
      M=0
      DO 10141 I=1,NIN
      M=M+1
      SUM=XFRM(M)
      DO 10151 J=1,NIN
      M=M+1
      SUM=SUM+XFRM(M)*VEC(J)
10151 CONTINUE
10152 CONTINUE
      VEC2(I)=SUM
10141 CONTINUE
10142 CONTINUE
      TEMP=1.0
      IF (NIN.GT.NOUT.and.VEC2(NIN).ne.0) TEMP=VEC2(NIN)
      DO 10161 I=1,NOUT
      VECOUT(I,NPT)=VEC2(I)/TEMP
10161 CONTINUE
10162 CONTINUE
10021 CONTINUE
10022 CONTINUE
      RETURN
      END
      SUBROUTINE T2IFRM(NIN,NUM,VECIN,ISCAL,XFRM1,NOUT,VECOUT)
      INTEGER NIN,NOUT,ISCAL(4)
      REAL XFRM1(12)
      REAL VECIN(NIN,NUM),VECOUT(NOUT,NUM),XFRM(12)
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL VEC(3),VEC2(3),LEAPYR,REGYR
      REAL DAYS(13)
      DATA DAYS/0.,31.,59.,90.,120.,151.,181.,212.,242.,273.,303.,334,10
     *00./
      M = NOUT
      N=0
      DO 10171 I=1,NOUT
      N=N+1
      XFRM(I)=XFRM1(N)
      DO 10181 J=1,nout
      M=M+1
      N=N+1
      XFRM(M)=XFRM1(N)
10181 CONTINUE
10182 CONTINUE
10171 CONTINUE
10172 CONTINUE
      IF(NOUT.eq.3 .and. XFRM(10).eq.0 .and. XFRM(11).eq.0 .and. XFRM(12
     *).eq.0) XFRM(12)=1
      CALL T2MINV(XFRM(NOUT+1),NOUT,DET)
      DO 10191 NPT=1,NUM
      DO 10201 I=1,NIN
      VEC2(I)=VECIN(I,NPT)
10201 CONTINUE
10202 CONTINUE
      IF (NIN.NE.NOUT) THEN
      VEC2(3)=XFRM(3)
      VEC2(1)=VEC2(1)*VEC2(3)
      VEC2(2)=VEC2(2)*VEC2(3)
      endif
      M=0
      DO 10211 I=1,NOUT
      M=M+1
      VEC2(I)=VEC2(I)-XFRM(M)
10211 CONTINUE
10212 CONTINUE
      DO 10221 I=1,NOUT
      SUM=0
      DO 10231 J=1,NOUT
      M=M+1
      SUM=SUM+XFRM(M)*VEC2(J)
10231 CONTINUE
10232 CONTINUE
      VEC(I) = SUM
10221 CONTINUE
10222 CONTINUE
      IF (ISCAL(4).NE.0 .AND. FLAGS(27)) then
      RAD2 = SQRT(VEC(1)**2+VEC(2)**2)
      THET1 = ATAN2(VEC(2),VEC(1))/RADANG
      IF(FLAGS(91))THEN
      RAD3 = SQRT(VEC(1)**2+VEC(2)**2+VEC(3)**2)
      VEC(3)= ATAN2(RAD2,VEC(3))/RADANG
      VEC(2) = RAD3
      VEC(1) = THET1
      ELSE
      VEC(2) = RAD2
      VEC(1) = THET1
      ENDIF
      endif
      DO 10241 I=1,NOUT
      IF (ISCAL(I).LT.0) then
10250 GOTO (10260,10270,10280,10290,10300,10310,10320,10330),-ISCAL(I)
10260 CONTINUE
      GOTO 10252
10270 CONTINUE
      VEC(I) = 10**VEC(I)
      GOTO 10252
10280 CONTINUE
      VEC(I) = -10**VEC(I)
      GOTO 10252
10300 CONTINUE
      LEAPS=(AINT(VEC(I))+1095)/1461
      T=VEC(I)-LEAPS
      JYEAR=T/365
      PART=T-JYEAR*365
      IF (PART.lt.0) THEN
      PART=PART+365
      JYEAR=JYEAR-1
      ENDIF
      VEC(I)=JYEAR+(PART+1)*0.001
      GOTO 10252
10290 CONTINUE
      T=VEC(I)
      LEAPS = T/1155
      T=T-LEAPS
      JYEAR = T/365
      PART = T-365*JYEAR
      IF (PART.lt.0) THEN
      PART=PART+365
      JYEAR=JYEAR-1
      ENDIF
      MONTH= 1
      JMIN=(PART+20)/30.
      JMIN=MIN(MAX(JMIN,1),12)
      DO 10341 J=JMIN,11
      IF (PART.ge.DAYS(J).and.PART.lt.DAYS(J+1)) THEN
      PART=PART-DAYS(J)
      MONTH=J
      GOTO 10342
      ENDIF
10341 CONTINUE
10342 CONTINUE
      VEC(I)= (PART+.5)*0.01+MONTH+JYEAR*12
      GOTO 10252
10310 CONTINUE
      XMIN=XYZLIM(I,1)
      XMAX=XYZLIM(I,2)
      YMIN=T2FRQF((XMIN-SCLPRM(2,I))/SCLPRM(3,I))
      YMAX=T2FRQF((XMAX-SCLPRM(2,I))/SCLPRM(3,I))
      T=VEC(I)
      DO 10351 J=1,6
      IF(ABS(YMAX-YMIN).le.0.0000002*T)GOTO 10352
      X=(T-YMIN)*(XMAX-XMIN)/(YMAX-YMIN)
      Y=T2FRQF((T-SCLPRM(2,I))/SCLPRM(3,I))
      IF (Y.gt.T) THEN
      XMAX=X
      YMAX=Y
      ELSE
      XMIN=X
      YMIN=Y
      ENDIF
10351 CONTINUE
10352 CONTINUE
      IF (ABS(VEC(I)-XMIN).lt.ABS(VEC(I)-XMAX)) THEN
      VEC(I)=XMIN
      ELSE
      VEC(I)=XMAX
      ENDIF
      GOTO 10252
10320 CONTINUE
      CONTINUE
      GOTO 10252
10330 CONTINUE
      TEMP=VEC(I)
      VEC(I)=SIGN(ABS(TEMP)**(1/SCLPRM(4,I)),TEMP)
      GOTO 10252
10252 CONTINUE
      ELSE
      VEC(I) = TDFNCT(VECIN(I,NPT),-ISCAL(I))
      ENDIF
10241 CONTINUE
10242 CONTINUE
      DO 10361 I=1,NOUT
      VECOUT(I,NPT)=VEC(I)
10361 CONTINUE
10362 CONTINUE
10191 CONTINUE
10192 CONTINUE
      RETURN
      END
      SUBROUTINE T2CROS(A,B,C)
      REAL A(3),B(3),C(3)
      C(1)=A(2)*B(3)-A(3)*B(2)
      C(2)=A(3)*B(1)-A(1)*B(3)
      C(3)=A(1)*B(2)-A(2)*B(1)
      RETURN
      END
      REAL FUNCTION T2FRQF(T)
      REAL A(6),SQT2
      DATA A/0.070523078,.042282012,.009270527 ,.000152014 , .000276567 
     *,.000043064 /
      DATA SQT2/ 1.414214/
      TT=ABS(T)/SQT2
      SUM=TT*(A(1)+TT*(A(2)+TT*(A(3)+TT*(A(4)+TT*(A(5)+TT*A(6))))))+1.0
      IF (SUM.GT.10.0) then
      T2FRQF=0.0
      ELSE
      T2FRQF = 0.5/SUM**16
      ENDIF
      IF (T.GT.0.) T2FRQF = 1.0-T2FRQF
      RETURN
      END
      SUBROUTINE T2MPRJ(XYLIM,XFRM)
      REAL XYLIM(2,2),XFRM(12)
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      REAL VECT1(3),VECT(3),UDIR(3),VDIR(3),HDIR(3),XHAT(3)
      REAL RAD
      PARAMETER (RAD=3.14159265/180.)
      DATA XHAT/1.,0.,0./
      FLAGS(61)=.FALSE.
      IF (FLAGS(56)) THEN
      T0=MAX(WORLD(1),MAX(WORLD(2),WORLD(3)))
      T1=(WINDOW(3)-WINDOW(1))/T0
      T2=(WINDOW(4)-WINDOW(2))/T0
      T=MIN(MAX(.01,MIN(T1,T2)),100.)
      CEYEDIS=EYEDIS
      IF (EYEDIS.LT.0.) CEYEDIS=ABS(EYEDIS)*REDUCE(2)
      IF (SCRD.LE.0.) THEN
      CSCRD=1.86*ABS(SCRD)*T
      ELSE
      CSCRD=SCRD
      ENDIF
      IF ((ABS(VERTCL(1))+ABS(VERTCL(2))+ABS(VERTCL(3))).EQ.0.0) THEN
      UDIR(1)=0.
      UDIR(2)=0.
      UDIR(3)=1.
      ELSE
      DO 10371 I=1,3
      UDIR(I)=VERTCL(I)
10371 CONTINUE
10372 CONTINUE
      ENDIF
      IF (.NOT.FLAGS(55) .OR. (ABS(EYEDIR(1))+ABS(EYEDIR(2))+ABS(EYEDIR(
     *3))).EQ.0.) THEN
      CALL T2CROS(UDIR,XHAT,VECT)
      IF (ABS(VECT(1))+ABS(VECT(2))+ABS(VECT(3)) .EQ.0.0) VECT(3)=1.
      CALL T2CROS(VECT,UDIR,HDIR)
      SINTH= SIN(TTHETA*RAD)
      COSTH= COS(TTHETA*RAD)
      SINPH=-SIN(TPHI  *RAD)
      COSPH=-COS(TPHI  *RAD)
      IF (REVLEV.lt.2.0) THEN
      T=SINTH
      SINTH=COSTH
      COSTH=T
      ENDIF
      DO 10381 I=1,3
      VDIR(I) = COSPH*UDIR(I) +  SINPH*(COSTH*HDIR(I) + SINTH*VECT(I))
      VECT1(I)= SINPH*UDIR(I) -  COSPH*(COSTH*HDIR(I) + SINTH*VECT(I))
10381 CONTINUE
10382 CONTINUE
      CALL T2CROS(VDIR,VECT1,VECT)
      ELSE
      DO 10391 I=1,3
      VDIR(I)=-EYEDIR(I)
10391 CONTINUE
10392 CONTINUE
      CALL T2CROS(UDIR,VDIR,VECT)
      ENDIF
      DO 10401 I=1,3
      IF (ABS(VUECEN(I)).GT.1000.) VUECEN(I)=0.5*WORLD(I)
10401 CONTINUE
10402 CONTINUE
      IF (ABS(VECT(1))+ABS(VECT(2))+ ABS(VECT(3)) .EQ. 0.) THEN
      IF (ABS(VDIR(1)) + ABS(VDIR(2)) .NE.0.0) THEN
      VECT(3)=1.0
      ELSE
      VECT(2)=1.0
      ENDIF
      ENDIF
      CALL T2CROS(VDIR,VECT,UDIR)
      TVR1=SQRT(VDIR(1)**2+VDIR(2)**2+VDIR(3)**2)
      TVR2=SQRT(UDIR(1)**2+UDIR(2)**2+UDIR(3)**2)
      DO 10411 I=1,3
      VDIR(I)=VDIR(I)/TVR1
      UDIR(I)=UDIR(I)/TVR2
      VUEDIR(I)=VDIR(I)
10411 CONTINUE
10412 CONTINUE
      CALL T2CROS(VDIR,UDIR,HDIR)
      TVR1=(WINDOW(3)-WINDOW(1))/(XYLIM(1,2)-XYLIM(1,1))
      TVR2=(WINDOW(4)-WINDOW(2))/(XYLIM(2,2)-XYLIM(2,1))
      TVR3=(TVR1*0.5*(XYLIM(1,2)+XYLIM(1,1))+EYESEP)/  (TVR1*CSCRD)
      TVR4=(0.5*(XYLIM(2,2)+XYLIM(2,1)))/CSCRD
      DO 10421 I=1,3
      XFRM(I+1)=HDIR(I)/TVR1+VDIR(I)*TVR3
      XFRM(I+5)=UDIR(I)/TVR2+VDIR(I)*TVR4
      XFRM(I+9)=VDIR(I)/CSCRD
      EYEPNT(I)=VUECEN(I)-VDIR(I)*CEYEDIS+EYESEP*HDIR(I)
10421 CONTINUE
10422 CONTINUE
      DO 10431 I=1,9,4
      XFRM(I)=-XFRM(I+1)*EYEPNT(1)-XFRM(I+2)*EYEPNT(2)  -XFRM(I+3)*EYEPN
     *T(3)
10431 CONTINUE
10432 CONTINUE
      ELSE
      DO 10441 I=1,12
      XFRM(I)=0.
10441 CONTINUE
10442 CONTINUE
      XFRM(2)=(XYLIM(1,2)-XYLIM(1,1))/WORLD(1)
      XFRM(1)=XYLIM(1,1)
      XFRM(7)=(XYLIM(2,2)-XYLIM(2,1))/WORLD(2)
      XFRM(5)=XYLIM(2,1)
      XFRM(9)=1.
      VUEDIR(1)=0.
      VUEDIR(2)=0.
      VUEDIR(3)=-1.
      EYEPNT(1)=0.
      EYEPNT(2)=0.
      EYEPNT(3)=18.
      ENDIF
      RETURN
      END
      SUBROUTINE T2AXST(XYZWRL,IXYZ,IAX2,IAX3,COSTX)
      IMPLICIT NONE
      INTEGER IXYZ,IAX2,IAX3
      REAL XYZWRL(3),COSTX
      COMMON /T2FLGC/ FLAGS(200), LTRAP,LHANDL,LSYERR,LSCREV
      LOGICAL FLAGS, LTRAP,LHANDL,LSYERR,LSCREV(3)
      INTEGER RELFLAG 
      PARAMETER (RELFLAG=151)
      INTEGER IWINLEV 
      INTEGER NWINLEV , MAX_FILL 
      PARAMETER (NWINLEV =4)
      PARAMETER (MAX_FILL=4)
      REAL GRDSYM, GRDSIZ, DATDAT(2,8), H2STAT(12), TITLIN(4), TITFA
     *C(4), TITLOC(4), TITMAR(4), TITLMX(4), TIKFAC, TITINX, TITX1, TIT
     *Y1, TITX, TITY, TITZ, TITSIZ, TITCON(5), REVLEV, REDUCE(5), XFR
     *M12(12), XFRM13(12), XFRM14(12), XFRM23(12), XFRM24(12), XFRM34(6
     *), XVARSX(20), CIRSIZ(2,3), ASIZE, AFLARE, SMSZDF, ORAXES(3), EY
     *EDIR(3), VUEDIR(3), VUECEN(3), VERTCL(3), EYESEP, SCRD, SCRZ, EYE
     *DIS, EYEPNT(3), XYPART(2, 2), BARSIZ(3), BARBRK(3), TIKSIZ(3), XY
     *ZBAS(3), TTHETA, TPHI, FRELBL(4), PATRN(20,30), SCLPRM(10,3), WI
     *NDOW(4), SCREEN(2), SYMBOL, NOSYMB, FACTXY(19), LBLSIZ, SYMSIZ, X
     *YZLIM(3,2), WORLD(3), RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY
     *0, XUNUSD(6), AXANG(3), REDFAC, DSCAL, PATSZ, MARGIN(4), PSCR(2
     *), OREAL, OCPU, CSCRD, DATPTS, ERRPTS, DATXMN, DATXMX, DATYMN, DA
     *TYMX, DATZMN, DATZMX, DATSUM, ERRSUM, DATAVE, ERRAVE, DATCEN, ERR
     *CEN, DATSTD, ERRSTD, WINREL(2,2,NWINLEV),WINABS(2,2,NWINLEV),WINL
     *IM(2,2), FMARKER(3,8), SYDIR(3), GRDIR(3), EXYZLIM(3,2), DSLOPE(2
     *,2)
      REAL PLOT_EXTENT(2,2),FILL_ANGLE(MAX_FILL),FILL_WIDTH(MAX_FILL)
      INTEGER FILL_INDEX, FILL_TEX(MAX_FILL), N_LINES(6)
      EQUIVALENCE (DATDAT, DATPTS)
      INTEGER MAXREP
      PARAMETER (MAXREP=5)
      INTEGER IPATRN, NPATRN(30), NXYLIM(3,2), NPLOTS, NCSETS, NCCOL, N
     *CROW, IYEAR, IMONTH, IDAY, ISIGFG, ITXPRI, ITXSEC, ITITDT(3), L
     *ENCRD, IPROP, IHTEX, IBLINK, IERASE, ITCNTR, IUNUSD, NXYZ1(3), 
     *NXYZ2(3), LBLFMT(3), LBLCHR(3), NDIMNS(3), IBLKTP, IDIMNS, NMES
     *H0, NMESH1, NMESH2, MESH1, MESH2, MESH3, MESH2D, MESHN(3), NMESHN(
     *2), NFIELD, IFIELD(19), NINCR, NPOINT, IVARBL(19), IVPTR(19), I_
     *VORDER(19,2), LINEAR(4), NONLIN(4), MXECHO, LINES, MAXLNS, USRK
     *BD, USRSCR, PLTFIL, LINWID, LINCOL, LINTEX, ICPOIN(3), IREPCT(MA
     *XREP), LEVREP, GRDTYP, GRDTEX, OUTTEX, IAXTEX, TITEX, LETSET, LAB
     *TEX, TICTEX, SHADOWTYP,SHADOWTEX, NXYZDEF1(10), NXYZDEF2(10), IF
     *ILE_CASE ,MAX_SUBST
      INTEGER MAX_CYCLE
      PARAMETER (MAX_CYCLE=20)
      INTEGER N_CYCLE, ITX_CYCLE(MAX_CYCLE)
      REAL SYM_CYCLE(MAX_CYCLE)
      EQUIVALENCE (NMESH1,NMESHN)
      EQUIVALENCE (MESH1,MESHN)
      INTEGER IBUFFR(400)
      REAL BUFFER(400)
      INTEGER NCHSAVE 
      PARAMETER (NCHSAVE=2*512) 
      INTEGER*4 ICHSAVE(NCHSAVE)
      INTEGER*4 IVRPTR(15)
      CHARACTER*512 OUTSTR,C_FILE, C_NAME, C_SELECT
      CHARACTER C_TIT_ESCAPE*1,C_TIT_SUBSTITUTE*2
      INTEGER N_FILE, N_NAME, N_SELECT
      CHARACTER*8 PXNAME
      CHARACTER*64 INPFMT
      LOGICAL LTDATA, OUTSID(4)
      COMMON /T2COM/ PXNAME, REDUCE, TITX, TITY ,XFRM12, XFRM13, XFRM1
     *4, XFRM23 ,XFRM24, XFRM34 ,XVARSX ,TITSIZ, GRDSYM, GRDSIZ, CIRS
     *IZ, ASIZE, AFLARE ,SMSZDF, ORAXES, EYEDIR, VUEDIR, VUECEN ,VERTC
     *L, EYESEP, SCRD, SCRZ, EYEDIS, EYEPNT ,XYPART, BARSIZ, TIKSIZ, XY
     *ZBAS, TTHETA ,TPHI, FRELBL, IPATRN, NPATRN, PATRN ,SCLPRM, WINDO
     *W, SCREEN, SYMBOL, NOSYMB ,FACTXY, LBLSIZ, SYMSIZ, XYZLIM, WORLD 
     *,RADRMX, RADRMN, RADAMN, RADANG, RADX0, RADY0, XUNUSD ,USRKBD, U
     *SRSCR, PLTFIL ,ITITDT, LENCRD ,INPFMT, GRDTYP, LINWID, LINCOL, L
     *INTEX, TITCON, ITCNTR ,IUNUSD, NXYZ1, NXYZ2 ,LBLCHR, NDIMNS, IBL
     *KTP, IDIMNS ,NMESH1, NMESH2, MESH1, MESH2, MESH3, NFIELD ,IFIELD
     *, NINCR ,IVARBL, IVRPTR ,LINEAR, NONLIN ,NPOINT, LETSET ,MXECH
     *O, LINES, MAXLNS ,AXANG, MESH2D, REDFAC, GRDTEX, OUTTEX, IAXTEX, 
     *TITEX, DSCAL ,OUTSTR, IPROP, IHTEX, IBLINK, IERASE, LABTEX, TICTE
     *X, NXYLIM, PATSZ ,MARGIN, PSCR, ITXPRI, ITXSEC, OREAL, OCPU, CSCR
     *D, OUTSID ,TITLIN, TITINX, TITZ, TITX1, TITY1, LTDATA, NPLOTS, RE
     *VLEV ,LBLFMT, IYEAR, IMONTH, IDAY, ISIGFG ,DATPTS, ERRPTS, DATXM
     *N, DATXMX, DATYMN, DATYMX, DATZMN, DATZMX ,DATSUM, ERRSUM, DATAVE
     *, ERRAVE, DATCEN, ERRCEN, DATSTD, ERRSTD ,NCSETS, NCCOL, NCROW, F
     *MARKER, H2STAT, TITFAC, TITLOC, TITMAR ,TIKFAC, IWINLEV, WINREL, 
     *WINABS, WINLIM ,ICPOIN, LEVREP, IREPCT, SYDIR, GRDIR, NMESH0, EXY
     *ZLIM, IVPTR ,TITLMX, NXYZDEF1, NXYZDEF2, IFILE_CASE, N_CYCLE, ITX
     *_CYCLE ,SYM_CYCLE, PLOT_EXTENT, FILL_ANGLE, FILL_WIDTH, FILL_TEX 
     *,FILL_INDEX ,N_LINES ,DSLOPE ,MAX_SUBST, BARBRK ,I_VORDER,SHADOW
     *TYP,SHADOWTEX
      COMMON /T2SCRT/ BUFFER, IBUFFR, N_FILE,N_NAME,N_SELECT, ICHSAVE
      COMMON /T2_CHAR/ C_TIT_ESCAPE,C_TIT_SUBSTITUTE
      COMMON /T2_SCRT/ C_FILE, C_NAME, C_SELECT
      INTEGER JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL, NINMAX
      PARAMETER (NINMAX=20)
      INTEGER NINP(NINMAX)
      COMMON /T2TRBK/NINP, JOUFIL, ERRFIL, OUTFIL, DBGFIL, INPFIL
      CHARACTER*512 STRNG, STJOU
      LOGICAL LTOKEN
      REAL FLOTNG
      INTEGER INTERP, KEYORD, NSTRNG, MAXSTR, NSTJOU, LSTJOU, NTOKEN
      INTEGER*4 INTEG
      COMMON /TOKENC/ INTERP, INTEG, FLOTNG, KEYORD, NSTRNG, MAXSTR, ST
     *RNG, NSTJOU, LSTJOU, STJOU, LTOKEN, NTOKEN
      INTEGER I,J
      REAL XYZ(3,4),XY(3),T2_DOT
      IAX2=IXYZ-1
      IF (IAX2.EQ.0) IAX2=3
      IAX3=6-IXYZ-IAX2
      DO 10451 J=1,4
      DO 10461 I=1,3
      XYZ(I,J)=0
10461 CONTINUE
10462 CONTINUE
10451 CONTINUE
10452 CONTINUE
      DO 10471 I=1,3
      XYZ(I,4)=XYZWRL(I)-EYEPNT(I)
      XYZ(I,I)=1
10471 CONTINUE
10472 CONTINUE
      DO 10481 I=1,3
      XY(I)=T2_DOT(XYZ(1,I),XYZ(1,4),3)
10481 CONTINUE
10482 CONTINUE
      IF (ABS(XY(IAX3)) .lt. ABS(XY(IAX2)) ) THEN
      I=IAX2
      IAX2=IAX3
      IAX3=I
      ENDIF
      IF(XYZWRL(IAX2)-VUECEN(IAX2).gt.0) COSTX=-1.0
      IF (XY(IAX3) .eq. 0) THEN
      IAX2=-IAX2
      ENDIF
      RETURN
      END
      SUBROUTINE T2XMUL(X1,X2,N,X3)
      INTEGER N
      REAL X1(12),X2(12),X3(12)
      J3=0
      NP1=N+1
      MAX=N*NP1
      DO 10491 I=1,MAX,NP1
      DO 10501 K1=1,4
      SUM=0.
      J1=I
      J2=K1
      DO 10511 J=1,3
      J1=J1+1
      SUM=SUM+X1(J1)*X2(J2)
      J2=J2+NP1
10511 CONTINUE
10512 CONTINUE
      J3=J3+1
      X3(J3)=SUM
10501 CONTINUE
10502 CONTINUE
10491 CONTINUE
10492 CONTINUE
      DO 10521 K=1,MAX,NP1
      X3(K)=X3(K)+X1(K)
10521 CONTINUE
10522 CONTINUE
      END
      SUBROUTINE T2MINV(ARRAY,N,DET)
C
C  MATRIX INVERSION ROUTINE--BEVINGTON,P.302
C
C  ARRAY IS THE SQUARE,SYMMETRIC MATRIX TO BE INVERTED
C  N IS THE ORDER, DET IS THE CALCULATED DETERMINANT
C  THE INVERTED MATRIX REPLACES THE ORIGINAL ONE
C
cThis routine has been optimized for virtual memory
c
      IMPLICITREAL*4 (A-H, O-Z)
      INTEGER    NMAX

      PARAMETER (NMAX=50) ! MAX NUMBER OF TERMS
      DIMENSION ARRAY(N,N)
      DIMENSION IK(NMAX),JK(NMAX)

      IF (N .gt. NMAX) THEN
        CALL T2STOP('-Array dimension larger than 50 in MATINV')
      ENDIF
      DET  = 1.

      DO 10 I = 1,N
        IK(I) = 0
 10     JK(I) = 0

      DO 100 K= 1,N
C
C  FIND LARGEST ELEMENT,REORDER SO IT IS ON THE DIAGONAL
C  PARTIAL PIVOTING
C
        AMAX      = 0.0
        DO 30 J      = K,N
          DO 30 I      = K,N
            IF(ABS(AMAX) .le. ABS(ARRAY(I,J))) THEN ! Larger element ?
              AMAX      = ARRAY(I,J)
              IK(K)     = I
              JK(K)     = J
            ENDIF
 30     CONTINUE
        IF(AMAX .eq. 0.) THEN   ! Matrix element too small ?
          DET      = 0.
          RETURN
        ENDIF
        I      = IK(K)
        IF(I.ne.K) THEN         ! Not Current col ?
          DO 50 J      = 1,N    ! Reorder columns
            SAVE       = ARRAY(K,J)
            ARRAY(K,J) = ARRAY(I,J)
 50         ARRAY(I,J) = -SAVE
        ENDIF
        J      = JK(K)
        IF(J.ne.K) THEN         ! Not Current row ?
          DO 60 I      = 1,N    ! Reorder rows
            SAVE       = ARRAY(I,K)
            ARRAY(I,K) = ARRAY(I,J)
 60         ARRAY(I,J) = -SAVE
        ENDIF

C  DIAGONALIZE MATRIX

        DO 70 I      = 1,N
          IF(I .ne. K) ARRAY(I,K)      = -ARRAY(I,K)/AMAX
 70     CONTINUE
        DO 80 J      = 1,N
          DO 80 I = 1,N
            IF(J.ne.K.and.I.ne.K)
     1        ARRAY(I,J)      = ARRAY(I,J)+ARRAY(I,K)*ARRAY(K,J)
 80     CONTINUE
        ARRAY(K,K)      = 1.
        DO 90 J      = 1,N
          ARRAY(K,J)      = ARRAY(K,J)/AMAX
 90     CONTINUE
 100    DET = DET * AMAX
C
C  RESTORE ORDERING OF MATRIX
C
 101  DO 130 L = 1,N
        K  = N-L+1
        J  = IK(K)
        IF(J.gt.K) THEN         ! Reorder ?
          DO 110 I     = 1,N
            SAVE       =  ARRAY(I,K)
            ARRAY(I,K) = -ARRAY(I,J)
 110        ARRAY(I,J) =  SAVE
        ENDIF
        I = JK(K)
        IF(I.gt.K) THEN         ! Reorder ?
          DO 120 J     = 1,N
            SAVE       =  ARRAY(K,J)
            ARRAY(K,J) = -ARRAY(I,J)
 120        ARRAY(I,J) =  SAVE
        ENDIF
 130  CONTINUE
      END
